window.MJ=window.MJ||{};MJ.content=MJ.content||{};
/* 질문 틀 (content/qtemplates.js) — 손으로 쓰는 본문. 규격은 DEV.md 4장.
 *
 * id      영역약자(st jy da jr ht gm cg an)-의도약자(m p c g e)+깊이(1 2 3)-일련번호
 * 자리표시 {칸|조사}  칸: topic concept book role subject result / 조사: 을 이 은 과 으로 이라는
 * needs   text 와 tails 에 쓴 칸 전부. 비어 있으면 지시어("이 활동", "이 수업")로 쓴 일반형.
 * cond    (선택 항목) 기록에 해당 사실이 있을 때만 쓰는 틀. 엔진이 걸러 쓴다.
 *         gwamok: nottaken(미이수) up(성적 상승) down(성적 하락) low(해당 과목 성적 낮음)
 *         chulgyeol: late(미인정 지각) absent(미인정 결석) leave(미인정 조퇴·결과) many(결석·조퇴 다수)
 * 고친 뒤에는 node pipeline/check_qt.js 로 검사한다.
 */
MJ.content.qt = [

  /* ════════ 교과 세부능력 및 특기사항 (seteuk) ════════ */
  // 선택·동기 · 깊이 1
  { id:"st-m1-01", area:["seteuk"], intent:"motive", depth:1, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 탐구 주제로 고른 계기는 무엇인가요?",
    purpose:"스스로 정한 주제인지, 호기심이 어디에서 출발했는지 확인합니다.",
    tails:["그 계기가 있기 전에는 이 주제를 어떻게 생각했나요?","계기에서 실제 탐구를 시작하기까지 무엇을 먼저 했나요?"] },
  { id:"st-m1-02", area:["seteuk"], intent:"motive", depth:1, kind:"experience", factor:"신뢰", needs:["topic"],
    text:"{topic|은} 선생님이 제시한 주제였나요, 스스로 정한 주제였나요?",
    purpose:"활동의 출발이 주어진 과제였는지 본인의 선택이었는지 사실을 확인합니다.",
    tails:["주제를 정할 때 참고한 자료나 수업 내용은 무엇이었나요?","그 주제 안에서 본인이 직접 정한 범위는 어디까지였나요?"] },
  { id:"st-m1-03", area:["seteuk"], intent:"motive", depth:1, kind:"experience", factor:"학업", needs:["subject"],
    text:"{subject} 수업의 어느 단원, 어떤 내용에서 이 탐구가 시작되었나요?",
    purpose:"탐구가 교과 수업과 실제로 이어져 있는지 확인합니다.",
    tails:["그 단원에서 특히 궁금했던 점은 무엇이었나요?","수업에서 배운 내용만으로 풀리지 않은 부분은 무엇이었나요?"] },
  { id:"st-m1-04", area:["seteuk"], intent:"motive", depth:1, kind:"experience", factor:"학업", needs:[],
    text:"이 활동은 수업 중 어떤 계기에서 시작되었나요?",
    purpose:"활동의 출발점과 자기주도성을 확인합니다.",
    tails:["그때 처음 떠올린 질문을 그대로 말해 줄 수 있나요?","그 질문은 활동을 하면서 어떻게 바뀌었나요?"] },
  { id:"st-m1-05", area:["seteuk"], intent:"motive", depth:1, kind:"experience", factor:"학업", needs:["book"],
    text:"{book|을} 읽게 된 계기는 무엇인가요? 스스로 고른 책이었나요?",
    purpose:"기록된 책을 실제로 스스로 골라 읽었는지 확인합니다.",
    tails:["같은 주제의 다른 책이 아니라 이 책을 고른 이유가 있나요?","읽기 전에 기대한 내용과 실제 내용은 어떻게 달랐나요?"] },
  { id:"st-m1-06", area:["seteuk"], intent:"motive", depth:1, kind:"experience", factor:"학업", needs:["concept"],
    text:"{concept|이라는} 개념에 관심을 갖게 된 계기는 무엇인가요?",
    purpose:"기록된 개념어가 본인의 관심에서 나온 것인지 확인합니다.",
    tails:["수업에서 처음 들었을 때 어떤 점이 궁금했나요?","그 궁금증을 풀려고 가장 먼저 한 일은 무엇인가요?"] },
  // 선택·동기 · 깊이 2
  { id:"st-m2-01", area:["seteuk"], intent:"motive", depth:2, kind:"opinion", factor:"학업", needs:["topic"],
    text:"여러 주제 가운데 {topic|을} 고른 이유는 무엇인가요? 함께 고민한 다른 주제도 말해 주세요.",
    purpose:"주제 선택에 본인의 판단 기준이 있었는지 확인합니다.",
    tails:["다른 주제를 내려놓은 기준은 무엇이었나요?","그 기준을 지금 돌아보면 적절했다고 생각하나요?"] },
  { id:"st-m2-02", area:["seteuk"], intent:"motive", depth:2, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic|이} 왜 탐구할 만한 주제라고 판단했나요?",
    purpose:"문제의식이 분명한지, 주제의 가치를 스스로 설명할 수 있는지 봅니다.",
    tails:["이미 알려진 내용과 본인이 새로 알아보려 한 내용을 구분해 말해 주세요.","이 주제가 밝혀지면 누구에게 어떤 도움이 되나요?"] },
  { id:"st-m2-03", area:["seteuk"], intent:"motive", depth:2, kind:"opinion", factor:"학업", needs:["subject"],
    text:"{subject} 과목의 여러 단원 가운데 이 내용을 깊이 파고든 이유는 무엇인가요?",
    purpose:"교과 안에서 관심 분야를 스스로 찾았는지 확인합니다.",
    tails:["다른 단원보다 이 내용에 더 끌린 까닭은 무엇인가요?","깊이 파고들면서 교과서 설명에서 아쉬웠던 점은 무엇인가요?"] },
  { id:"st-m2-04", area:["seteuk"], intent:"motive", depth:2, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동을 시작할 때 스스로 세운 질문은 무엇이었고, 왜 그 질문이 중요하다고 보았나요?",
    purpose:"활동이 수동적인 수행이었는지, 스스로 문제를 찾은 것인지 확인합니다.",
    tails:["처음 질문이 활동 중에 바뀐 적이 있나요?","그 질문을 더 좋은 질문으로 고친다면 어떻게 고치겠습니까?"] },
  { id:"st-m2-05", area:["seteuk"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic|은} 지원한 전공과 어떤 관련이 있어서 고른 주제인가요?",
    purpose:"교과 활동과 진로 관심이 이어져 있는지 확인합니다.",
    tails:["전공과 직접 관련이 없었더라도 이 주제를 골랐을까요?","이 주제를 다루면서 전공에 대한 생각이 달라진 점이 있나요?"] },
  { id:"st-m2-06", area:["seteuk"], intent:"motive", depth:2, kind:"opinion", factor:"학업", needs:["book"],
    text:"{book|을} 탐구의 참고 자료로 고른 이유는 무엇인가요?",
    purpose:"자료를 고르는 기준이 있었는지, 책을 실제로 활용했는지 확인합니다.",
    tails:["그 책에서 탐구에 실제로 쓴 내용은 어느 부분인가요?","그 책만으로 부족했던 내용은 어떻게 채웠나요?"] },
  // 선택·동기 · 깊이 3
  { id:"st-m3-01", area:["seteuk"], intent:"motive", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"지금 다시 주제를 정한다면 {topic|을} 그대로 고르겠습니까, 바꾸겠습니까? 이유도 말해 주세요.",
    purpose:"자신의 선택을 돌아보고 비판적으로 평가할 수 있는지 봅니다.",
    tails:["바꾼다면 범위를 넓히겠습니까, 좁히겠습니까?","그렇게 바꾸면 탐구 방법은 어떻게 달라지나요?"] },
  { id:"st-m3-02", area:["seteuk"], intent:"motive", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic|은} 범위가 넓은 주제일 수 있습니다. 어디까지 다루고 어디부터는 다루지 않았나요?",
    purpose:"탐구 범위를 스스로 정하고 그 한계를 알고 있는지 확인합니다.",
    tails:["다루지 않은 부분 때문에 결론이 달라질 가능성은 없나요?","시간이 더 있었다면 어느 부분을 추가했겠습니까?"] },
  { id:"st-m3-03", area:["seteuk"], intent:"motive", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"누군가 {topic|은} 이미 답이 나와 있는 주제라고 말한다면 어떻게 답하겠습니까?",
    purpose:"반대 의견 앞에서 탐구의 의미를 근거 있게 설명하는지 봅니다.",
    tails:["본인의 탐구에서 기존 설명과 달랐던 점은 무엇인가요?","새로 알아낸 것이 없었다면 이 탐구의 의미는 무엇이라고 보나요?"] },
  { id:"st-m3-04", area:["seteuk"], intent:"motive", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"이 주제를 고른 것이 좋은 선택이었는지 지금 평가한다면 어떻게 말하겠습니까?",
    purpose:"활동을 한 발 떨어져 평가하는 성찰 능력을 확인합니다.",
    tails:["그렇게 평가하는 기준은 무엇인가요?","같은 수업을 듣는 후배에게는 어떤 주제를 권하겠습니까?"] },
  // 과정·역할 · 깊이 1
  { id:"st-p1-01", area:["seteuk"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:["topic"],
    text:"{topic|을} 다룬 활동에서 본인이 직접 한 부분은 어디까지인가요?",
    purpose:"기록된 활동에서 본인의 실제 역할과 기여도를 확인합니다.",
    tails:["그중 시간이 가장 많이 든 일은 무엇이었나요?","다른 사람의 도움을 받은 부분은 어디였나요?"] },
  { id:"st-p1-02", area:["seteuk"], intent:"process", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡았다고 되어 있습니다. 실제로 어떤 일을 했는지 순서대로 말해 주세요.",
    purpose:"기록된 역할을 실제로 수행했는지 사실을 확인합니다.",
    tails:["그 역할은 어떻게 맡게 되었나요?","그 역할을 하면서 가장 판단하기 어려웠던 순간은 언제였나요?"] },
  { id:"st-p1-03", area:["seteuk"], intent:"process", depth:1, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic}에 대해 조사할 때 어떤 자료를 찾아보았나요?",
    purpose:"자료를 직접 찾고 읽었는지 확인합니다.",
    tails:["그 자료는 어떤 경로로 찾았나요?","자료끼리 내용이 서로 달랐던 적은 없었나요?"] },
  { id:"st-p1-04", area:["seteuk"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"이 활동을 처음부터 끝까지 어떤 순서로 진행했는지 간단히 말해 주세요.",
    purpose:"활동의 전체 과정을 직접 겪었는지 확인합니다.",
    tails:["그 가운데 계획과 다르게 진행된 단계는 어디였나요?","전체 과정에 시간은 얼마나 들었나요?"] },
  { id:"st-p1-05", area:["seteuk"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:["result"],
    text:"기록에 {result|이} 나옵니다. 본인이 직접 얻은 결과인가요, 자료에서 확인한 내용인가요?",
    purpose:"결과가 본인의 탐구에서 나온 것인지 진위를 확인합니다.",
    tails:["그 결과를 얻기까지 거친 과정을 단계별로 말해 주세요.","결과를 정리할 때 본인이 직접 판단한 부분은 무엇인가요?"] },
  { id:"st-p1-06", area:["seteuk"], intent:"process", depth:1, kind:"experience", factor:"소통", needs:[],
    text:"이 탐구 결과를 수업에서 발표했나요? 발표에서 본인이 맡은 부분은 무엇이었나요?",
    purpose:"발표 경험과 전달 과정에서의 역할을 확인합니다.",
    tails:["듣는 친구들이 가장 어려워한 내용은 무엇이었나요?","그 부분을 어떻게 풀어서 설명했나요?"] },
  // 과정·역할 · 깊이 2
  { id:"st-p2-01", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다룰 때 어떤 방법을 썼고, 왜 그 방법을 택했나요?",
    purpose:"탐구 방법을 근거를 가지고 골랐는지 확인합니다.",
    tails:["다른 방법도 검토했나요? 그 방법을 택하지 않은 이유는 무엇인가요?","택한 방법으로는 확인할 수 없는 것은 무엇이었나요?"] },
  { id:"st-p2-02", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다루면서 처음에 세운 가설이나 예상은 무엇이었나요?",
    purpose:"예측하고 검증하는 탐구의 틀을 갖추었는지 확인합니다.",
    tails:["그렇게 예상한 근거는 무엇이었나요?","예상과 결과가 달랐다면 어디에서 달라졌다고 보나요?"] },
  { id:"st-p2-03", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다루는 과정에서 가장 막혔던 지점은 어디였고, 어떻게 풀었나요?",
    purpose:"어려움을 만났을 때의 문제 해결 과정을 확인합니다.",
    tails:["스스로 해결한 부분과 도움을 받은 부분을 나누어 말해 주세요.","같은 문제가 다시 생기면 이번에는 어떻게 하겠습니까?"] },
  { id:"st-p2-04", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"이 탐구에서 비교한 대상은 무엇이었고, 비교를 위해 같게 맞춘 조건은 무엇이었나요?",
    purpose:"변인과 조건을 의식하며 탐구를 설계했는지 확인합니다.",
    tails:["조건을 같게 유지하려고 실제로 어떻게 했나요?","미처 맞추지 못한 조건이 결과에 영향을 주었을 가능성은 없나요?"] },
  { id:"st-p2-05", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"참고한 자료가 믿을 만하다고 판단한 기준은 무엇이었나요?",
    purpose:"자료의 출처와 신뢰성을 따져 보는 태도를 확인합니다.",
    tails:["자료의 출처는 어떻게 확인했나요?","서로 다른 주장을 하는 자료가 있었다면 어느 쪽을 따랐고, 이유는 무엇인가요?"] },
  { id:"st-p2-06", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["result"],
    text:"{result|은} 어떤 자료나 과정에서 나온 것인가요? 근거를 설명해 주세요.",
    purpose:"결론과 근거가 논리적으로 이어지는지 확인합니다.",
    tails:["그 근거만으로 충분하다고 판단한 이유는 무엇인가요?","같은 자료를 보고 다른 결론을 내릴 수도 있지 않을까요?"] },
  { id:"st-p2-07", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡은 동안 모둠에서 의견이 갈렸을 때는 어떻게 정리했나요?",
    purpose:"협업 과정에서의 조정 방식과 소통 태도를 확인합니다.",
    tails:["받아들이지 않은 의견은 무엇이었고, 왜 그랬나요?","그 결정을 아쉬워한 친구에게는 어떻게 했나요?"] },
  { id:"st-p2-08", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"탐구 중에 예상과 다른 결과가 나온 적이 있었나요? 그때 어떻게 대응했나요?",
    purpose:"예상 밖의 결과를 다루는 태도와 원인 분석 능력을 확인합니다.",
    tails:["원인을 무엇이라고 판단했고, 그 판단을 어떻게 확인했나요?","그 일로 탐구 계획에서 바꾼 부분은 무엇인가요?"] },
  { id:"st-p2-09", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["book"],
    text:"{book}의 내용을 탐구에 어떻게 활용했는지 구체적으로 말해 주세요.",
    purpose:"책을 읽는 데 그치지 않고 탐구에 실제로 썼는지 확인합니다.",
    tails:["책의 어느 부분이 가장 쓸모 있었나요?","책의 설명과 본인의 탐구 결과가 어긋난 부분은 없었나요?"] },
  { id:"st-p2-10", area:["seteuk"], intent:"process", depth:2, kind:"concept", factor:"학업", needs:["subject"],
    text:"{subject} 수업에서 배운 내용 가운데 이 탐구에 실제로 쓴 것은 무엇인가요?",
    purpose:"교과에서 배운 지식을 탐구에 적용했는지 확인합니다.",
    tails:["수업 내용만으로 부족했던 부분은 무엇이었나요?","그 부분은 무엇을 찾아보며 채웠나요?"] },
  // 과정·역할 · 깊이 3
  { id:"st-p3-01", area:["seteuk"], intent:"process", depth:3, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다룬 방법에서 가장 아쉬운 점은 무엇이고, 다시 한다면 어떻게 바꾸겠습니까?",
    purpose:"탐구 방법의 한계를 알고 개선안을 낼 수 있는지 봅니다.",
    tails:["그렇게 바꾸면 결과가 어떻게 달라질 것으로 예상하나요?","바꾼 방법에도 남는 한계는 무엇인가요?"] },
  { id:"st-p3-02", area:["seteuk"], intent:"process", depth:3, kind:"experience", factor:"학업", needs:[],
    text:"사용한 자료나 측정값에는 어떤 한계가 있었나요? 그 한계가 결론에 어떤 영향을 주나요?",
    purpose:"자료의 한계와 결론의 범위를 구분해 생각하는지 확인합니다.",
    tails:["그 한계를 줄이려면 무엇이 더 필요했나요?","보고서나 발표에서 그 한계를 밝혔나요?"] },
  { id:"st-p3-03", area:["seteuk"], intent:"process", depth:3, kind:"opinion", factor:"학업", needs:["result"],
    text:"{result|을} 믿을 수 있으려면 어떤 추가 확인이 필요하다고 생각하나요?",
    purpose:"결론을 검증하는 방법을 스스로 설계할 수 있는지 봅니다.",
    tails:["그 확인을 고등학교에서 할 수 있는 방법이 있나요?","확인 결과가 반대로 나오면 결론을 어떻게 고치겠습니까?"] },
  { id:"st-p3-04", area:["seteuk"], intent:"process", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"시간과 장비가 충분했다면 {topic|을} 어떤 방법으로 다시 탐구하겠습니까?",
    purpose:"조건이 달라졌을 때 더 나은 탐구를 설계하는 능력을 봅니다.",
    tails:["그 방법이 지금 쓴 방법보다 나은 점은 무엇인가요?","그 방법을 쓰려면 어떤 지식이 더 필요한가요?"] },
  { id:"st-p3-05", area:["seteuk"], intent:"process", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"같은 탐구를 대상이나 표본을 바꿔서 한다면 결과가 같을까요? 이유를 말해 주세요.",
    purpose:"결과가 어느 범위까지 통하는지 추론하는 능력을 확인합니다.",
    tails:["결과가 달라진다면 어떤 요인 때문일까요?","그렇다면 지금 결론은 어느 범위까지 맞다고 말할 수 있나요?"] },
  { id:"st-p3-06", area:["seteuk"], intent:"process", depth:3, kind:"opinion", factor:"공동체", needs:["role"],
    text:"{role|을} 다시 맡는다면 진행 방식에서 무엇을 다르게 하겠습니까?",
    purpose:"역할 수행을 돌아보고 개선점을 찾는지 확인합니다.",
    tails:["그렇게 바꾸려는 이유가 된 장면이 있나요?","바꾼 방식에 반대하는 친구가 있다면 어떻게 설득하겠습니까?"] },
  // 개념·원리 · 깊이 1
  { id:"st-c1-01", area:["seteuk"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|이} 무엇인지 한두 문장으로 설명해 보세요.",
    purpose:"기록된 개념을 자기 말로 정확히 정의할 수 있는지 확인합니다.",
    tails:["방금 설명에 쓴 용어 가운데 하나를 골라 더 쉽게 풀어 보세요.","이 개념을 처음 배울 때 헷갈렸던 점은 무엇이었나요?","이 개념이 쓰이는 예를 하나 들어 보세요."] },
  { id:"st-c1-02", area:["seteuk"], intent:"concept", depth:1, kind:"concept", factor:"신뢰", needs:["concept"],
    text:"세특에 {concept|이라는} 용어가 나옵니다. 어떤 맥락에서 쓴 말인가요?",
    purpose:"기록에 있는 전문 용어를 실제로 이해하고 썼는지 확인합니다.",
    tails:["그 용어를 쓰지 않고 같은 내용을 설명해 볼 수 있나요?","이 용어는 수업에서 배운 것인가요, 따로 찾아본 것인가요?"] },
  { id:"st-c1-03", area:["seteuk"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["topic"],
    text:"{topic}에서 가장 핵심이 되는 개념 하나를 꼽고, 뜻을 말해 보세요.",
    purpose:"탐구 주제의 바탕이 되는 개념을 짚어 낼 수 있는지 봅니다.",
    tails:["그 개념이 왜 핵심이라고 생각하나요?","그 개념을 모르면 이 주제에서 무엇을 이해할 수 없나요?"] },
  { id:"st-c1-04", area:["seteuk"], intent:"concept", depth:1, kind:"concept", factor:"소통", needs:[],
    text:"이 활동에서 다룬 핵심 개념을 중학생도 알아듣게 설명해 보세요.",
    purpose:"개념을 이해한 깊이와 쉽게 전달하는 능력을 함께 봅니다.",
    tails:["방금 설명이 실제 개념과 정확히 맞지 않는 부분은 어디인가요?","그 개념과 함께 알아야 하는 다른 개념은 무엇인가요?"] },
  { id:"st-c1-05", area:["seteuk"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["book"],
    text:"{book}의 핵심 주장을 두세 문장으로 정리해 보세요.",
    purpose:"기록된 책을 실제로 읽고 내용을 파악했는지 확인합니다.",
    tails:["저자가 그 주장을 뒷받침하려고 든 근거는 무엇인가요?","그 근거 가운데 설득력이 가장 약하다고 느낀 것은 무엇인가요?"] },
  { id:"st-c1-06", area:["seteuk"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["subject"],
    text:"{subject} 과목에서 배운 개념 가운데 가장 자신 있는 것 하나를 골라 설명해 보세요.",
    purpose:"교과의 기초 개념을 정확히 알고 있는지 확인합니다.",
    tails:["그 개념을 배우기 전에 먼저 알아야 하는 내용은 무엇인가요?","그 개념이 쓰이는 문제 상황을 하나 들어 보세요."] },
  // 개념·원리 · 깊이 2
  { id:"st-c2-01", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept}의 원리를 차근차근 설명해 보세요.",
    purpose:"개념의 원리를 단계적으로 설명할 수 있는지 확인합니다.",
    tails:["방금 설명에서 한 부분이 빠지면 무엇이 설명되지 않나요?","이 원리를 뒷받침하는 관찰이나 사례는 무엇인가요?"] },
  { id:"st-c2-02", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|이} 일상에서 나타나는 사례를 하나 들고, 왜 그 사례에 해당하는지 설명해 보세요.",
    purpose:"개념을 실제 상황에 연결해 이해하고 있는지 봅니다.",
    tails:["그 사례에서 개념과 정확히 맞지 않는 부분은 없나요?","성격이 다른 사례를 하나 더 든다면 무엇인가요?"] },
  { id:"st-c2-03", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|과} 헷갈리기 쉬운 개념은 무엇이고, 둘은 어떻게 다른가요?",
    purpose:"비슷한 개념을 구분할 만큼 정확히 이해했는지 확인합니다.",
    tails:["두 개념을 구분해야 하는 상황을 예로 들어 보세요.","두 개념에 공통으로 깔린 원리는 무엇인가요?"] },
  { id:"st-c2-04", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["topic","concept"],
    text:"{topic|을} 설명하는 데 {concept|이} 왜 필요한가요?",
    purpose:"개념과 탐구 주제의 관계를 이해하고 있는지 확인합니다.",
    tails:["이 개념 없이 설명하려면 어디에서 막히나요?","이 주제에 함께 쓰인 다른 개념은 무엇인가요?"] },
  { id:"st-c2-05", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:[],
    text:"이 활동의 결과를 교과서에 나오는 원리로 설명해 보세요.",
    purpose:"활동 결과를 교과 개념으로 해석할 수 있는지 확인합니다.",
    tails:["그 원리로 설명되지 않는 부분은 없었나요?","그 원리는 어느 과목, 어느 단원에서 배웠나요?"] },
  { id:"st-c2-06", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["result"],
    text:"{result|을} 교과 개념으로 설명하면 어떻게 되나요?",
    purpose:"결과가 나온 이유를 원리 수준에서 이해하는지 확인합니다.",
    tails:["그 설명에서 전제로 삼은 조건은 무엇인가요?","그 조건이 맞지 않는 경우를 하나 들어 보세요."] },
  { id:"st-c2-07", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["book"],
    text:"{book}에 나온 내용 가운데 수업에서 배운 개념과 이어지는 부분을 설명해 보세요.",
    purpose:"독서와 교과 학습을 연결해 이해했는지 확인합니다.",
    tails:["책의 설명이 교과서보다 더 나아간 부분은 무엇인가요?","책을 읽고 나서 그 개념에 대한 이해가 어떻게 달라졌나요?"] },
  { id:"st-c2-08", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["subject"],
    text:"{subject} 세특에 적힌 내용 가운데 가장 어려웠던 개념은 무엇이고, 어떻게 이해했나요?",
    purpose:"어려운 개념을 끝까지 이해하려 한 과정과 현재 이해 수준을 봅니다.",
    tails:["지금 그 개념을 간단히 설명해 보세요.","아직 완전히 이해하지 못한 부분이 있다면 무엇인가요?"] },
  { id:"st-c2-09", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|이} 나타나거나 성립하려면 어떤 조건이 필요한가요?",
    purpose:"개념이 적용되는 조건과 범위를 알고 있는지 확인합니다.",
    tails:["그 조건이 갖춰졌는지는 어떻게 확인하나요?","조건 하나가 빠진 예를 들어 보세요."] },
  { id:"st-c2-10", area:["seteuk"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|을} 이 탐구에서는 어떻게 측정하거나 확인했나요?",
    purpose:"추상적인 개념을 구체적인 방법으로 옮겼는지 확인합니다.",
    tails:["그 방법이 개념을 제대로 반영한다고 본 이유는 무엇인가요?","더 정확하게 확인하려면 무엇이 달라져야 하나요?"] },
  // 개념·원리 · 깊이 3
  { id:"st-c3-01", area:["seteuk"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|과} 관련된 조건 하나가 달라지면 결과가 어떻게 바뀌는지 예를 들어 설명해 보세요.",
    purpose:"원리를 이해하고 새로운 조건에 적용해 추론하는지 봅니다.",
    tails:["그렇게 예측한 근거는 무엇인가요?","그 예측을 확인하려면 어떤 실험이나 자료가 필요한가요?"] },
  { id:"st-c3-02", area:["seteuk"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|으로} 설명되지 않는 사례나 예외가 있다면 무엇인가요?",
    purpose:"개념의 한계와 적용 범위를 알고 있는지 확인합니다.",
    tails:["그 예외는 왜 생긴다고 생각하나요?","예외까지 설명하려면 어떤 개념이 더 필요한가요?"] },
  { id:"st-c3-03", area:["seteuk"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|을} 다른 과목이나 다른 분야에 적용한 예를 하나 들어 보세요.",
    purpose:"배운 개념을 다른 맥락으로 옮겨 쓸 수 있는지 확인합니다.",
    tails:["두 분야에서 이 개념은 같은 뜻으로 쓰이나요, 다르게 쓰이나요?","그 적용이 맞지 않는 지점은 어디인가요?"] },
  { id:"st-c3-04", area:["seteuk"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:[],
    text:"이 활동에서 쓴 설명이 실제 현상을 단순하게 본 부분이 있다면 어디인가요?",
    purpose:"자신의 설명이 가진 가정과 한계를 인식하는지 봅니다.",
    tails:["그렇게 단순하게 보아서 놓친 것은 무엇인가요?","더 정확히 설명하려면 무엇을 더 배워야 하나요?"] },
  { id:"st-c3-05", area:["seteuk"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|과} 겉으로는 비슷해 보이지만 원리가 다른 사례를 하나 들고, 차이를 설명해 보세요.",
    purpose:"겉모습이 아니라 원리로 대상을 구분하는지 확인합니다.",
    tails:["둘을 구별할 수 있는 기준이나 방법은 무엇인가요?","겉으로 비슷해 보이는 이유는 무엇인가요?"] },
  { id:"st-c3-06", area:["seteuk"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["result"],
    text:"{result|이} 성립하지 않는 조건이 있다면 어떤 경우일까요?",
    purpose:"결론의 적용 범위와 반례를 생각해 보았는지 확인합니다.",
    tails:["그 경우를 확인할 방법이 있을까요?","그렇다면 결론을 어떻게 고쳐 써야 정확할까요?"] },
  { id:"st-c3-07", area:["seteuk"], intent:"concept", depth:3, kind:"opinion", factor:"학업", needs:["book"],
    text:"{book}의 주장 가운데 동의하지 않는 부분이 있나요? 근거와 함께 말해 주세요.",
    purpose:"책을 비판적으로 읽었는지, 자기 관점이 있는지 확인합니다.",
    tails:["저자가 그 반론을 듣는다면 어떻게 답할 것 같나요?","책이 쓰인 때와 지금은 무엇이 달라졌나요?"] },
  // 배움·변화 · 깊이 1
  { id:"st-g1-01", area:["seteuk"], intent:"growth", depth:1, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다루고 나서 새로 알게 된 사실 한 가지를 말해 주세요.",
    purpose:"활동에서 실제로 얻은 배움이 있는지 확인합니다.",
    tails:["그 사실을 알기 전에는 어떻게 생각하고 있었나요?","그 사실은 어디에서 확인했나요?"] },
  { id:"st-g1-02", area:["seteuk"], intent:"growth", depth:1, kind:"experience", factor:"학업", needs:[],
    text:"이 수업을 듣기 전과 후에 달라진 점을 한 가지만 말해 주세요.",
    purpose:"수업을 통한 변화를 스스로 인식하는지 확인합니다.",
    tails:["달라졌다는 것을 스스로 느낀 장면이 있나요?","그 변화가 다른 과목 공부에도 이어졌나요?"] },
  { id:"st-g1-03", area:["seteuk"], intent:"growth", depth:1, kind:"experience", factor:"학업", needs:["subject"],
    text:"{subject} 수업에서 가장 기억에 남는 활동은 무엇이고, 무엇을 배웠나요?",
    purpose:"과목에 대한 몰입과 배움의 내용을 확인합니다.",
    tails:["그 활동이 기억에 남는 이유는 무엇인가요?","그때 배운 것을 지금도 쓰고 있나요?"] },
  { id:"st-g1-04", area:["seteuk"], intent:"growth", depth:1, kind:"concept", factor:"학업", needs:["book"],
    text:"{book|을} 읽고 가장 기억에 남은 내용은 무엇인가요?",
    purpose:"책의 내용을 구체적으로 기억하고 있는지 확인합니다.",
    tails:["그 내용이 왜 기억에 남았나요?","그 내용을 계기로 더 찾아본 것이 있나요?"] },
  { id:"st-g1-05", area:["seteuk"], intent:"growth", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡으면서 배운 점을 한 가지 말해 주세요.",
    purpose:"역할 경험에서 얻은 배움이 구체적인지 확인합니다.",
    tails:["그 배움을 얻은 장면을 말해 주세요.","그 뒤 다른 모둠 활동에서 실제로 달라진 행동이 있나요?"] },
  // 배움·변화 · 깊이 2
  { id:"st-g2-01", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다루면서 처음 생각이 바뀐 부분이 있나요? 무엇이 생각을 바꾸었나요?",
    purpose:"근거를 만나 생각을 고치는 유연한 태도를 확인합니다.",
    tails:["바뀌기 전 생각에도 타당한 면이 있었나요?","바뀐 생각을 다시 흔들 만한 근거가 있다면 무엇일까요?"] },
  { id:"st-g2-02", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다루면서 잘못 알고 있던 내용을 바로잡은 경험이 있나요?",
    purpose:"자신의 이해를 점검하고 고친 경험을 확인합니다.",
    tails:["잘못 알고 있었다는 것을 어떻게 알아차렸나요?","바로잡은 이해가 맞는지는 어떻게 확인했나요?"] },
  { id:"st-g2-03", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"이 활동을 하면서 공부하는 방법이나 태도에서 달라진 점은 무엇인가요?",
    purpose:"활동이 학습 태도의 변화로 이어졌는지 확인합니다.",
    tails:["달라진 방법을 다른 과목에 쓴 사례가 있나요?","예전 방식의 문제는 무엇이었다고 보나요?"] },
  { id:"st-g2-04", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:["concept"],
    text:"{concept|을} 이해하고 나서 같은 과목의 다른 단원을 보는 눈이 어떻게 달라졌나요?",
    purpose:"개념 이해가 다른 학습으로 넓어졌는지 확인합니다.",
    tails:["달라진 것을 느낀 단원이나 문제를 예로 들어 주세요.","아직 연결이 잘 안 되는 단원은 어디인가요?"] },
  { id:"st-g2-05", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:["subject"],
    text:"{subject} 과목을 공부하면서 가장 크게 자랐다고 느끼는 능력은 무엇인가요?",
    purpose:"과목 학습을 통한 성장을 스스로 설명할 수 있는지 봅니다.",
    tails:["그 능력이 드러난 장면을 하나 말해 주세요.","아직 부족하다고 느끼는 부분은 무엇인가요?"] },
  { id:"st-g2-06", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"소통", needs:[],
    text:"탐구 결과를 발표한 뒤 받은 질문이나 지적 가운데 기억에 남는 것은 무엇인가요?",
    purpose:"다른 사람의 의견을 듣고 받아들이는 태도를 확인합니다.",
    tails:["그 자리에서는 어떻게 답했나요?","지금 다시 답한다면 무엇을 덧붙이겠습니까?"] },
  { id:"st-g2-07", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:["book"],
    text:"{book|을} 읽은 뒤 생각이나 행동에서 달라진 점은 무엇인가요?",
    purpose:"독서가 실제 변화로 이어졌는지 확인합니다.",
    tails:["달라진 행동을 구체적인 사례로 말해 주세요.","그 변화에 책 말고 다른 영향은 없었나요?"] },
  // 배움·변화 · 깊이 3
  { id:"st-g3-01", area:["seteuk"], intent:"growth", depth:3, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic|을} 다루며 배운 것을 대학 전공 공부에 어떻게 이어 가겠습니까?",
    purpose:"고교 활동의 배움을 대학 학업으로 넓혀 생각하는지 봅니다.",
    tails:["그러려면 대학에서 어떤 과목을 먼저 들어야 한다고 생각하나요?","지금 수준에서 가장 보완해야 할 지식은 무엇인가요?"] },
  { id:"st-g3-02", area:["seteuk"], intent:"growth", depth:3, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다루고도 아직 풀리지 않은 궁금증은 무엇인가요?",
    purpose:"배움 뒤에 남은 질문이 있는지, 지적 호기심이 이어지는지 봅니다.",
    tails:["그 궁금증을 풀려면 어떤 방법이 필요할까요?","고등학교 과정에서는 왜 풀기 어려웠나요?"] },
  { id:"st-g3-03", area:["seteuk"], intent:"growth", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동에서 얻은 배움을 전혀 다른 상황에 적용한다면 어떤 예가 있을까요?",
    purpose:"배운 것을 새로운 맥락으로 옮겨 쓰는 능력을 확인합니다.",
    tails:["그 상황에서도 같은 방식이 통한다고 보는 이유는 무엇인가요?","통하지 않는 부분이 있다면 무엇을 바꿔야 하나요?"] },
  { id:"st-g3-04", area:["seteuk"], intent:"growth", depth:3, kind:"experience", factor:"학업", needs:[],
    text:"이 활동을 돌아볼 때 스스로 가장 부족했다고 평가하는 부분은 무엇인가요?",
    purpose:"자신의 부족함을 정직하게 보고 보완하려는지 확인합니다.",
    tails:["그 부족함을 채우려고 그 뒤에 한 일이 있나요?","같은 부족함이 대학 공부에서 드러난다면 어떻게 하겠습니까?"] },
  { id:"st-g3-05", area:["seteuk"], intent:"growth", depth:3, kind:"opinion", factor:"학업", needs:["concept"],
    text:"{concept|을} 배운 것이 사회나 일상의 문제를 보는 관점에 어떤 영향을 주었나요?",
    purpose:"교과 지식이 세상을 보는 관점으로 이어졌는지 봅니다.",
    tails:["그 관점으로 최근에 본 사례를 하나 말해 주세요.","그 관점만으로는 놓치기 쉬운 것은 무엇인가요?"] },
  // 확장·가정 · 깊이 1
  { id:"st-e1-01", area:["seteuk"], intent:"extend", depth:1, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 다룬 뒤에 이어서 한 활동이나 공부가 있나요?",
    purpose:"관심이 한 번의 활동으로 끝났는지 이어졌는지 확인합니다.",
    tails:["이어서 하게 된 이유는 무엇인가요?","앞의 활동과 달라진 점은 무엇인가요?"] },
  { id:"st-e1-02", area:["seteuk"], intent:"extend", depth:1, kind:"experience", factor:"학업", needs:[],
    text:"이 탐구가 다른 과목이나 다른 학년의 활동으로 이어진 것이 있나요?",
    purpose:"학생부 기록 사이의 연결과 관심의 지속성을 확인합니다.",
    tails:["두 활동을 잇는 공통 질문은 무엇인가요?","이어지는 과정에서 관심이 넓어졌나요, 좁혀졌나요?"] },
  { id:"st-e1-03", area:["seteuk"], intent:"extend", depth:1, kind:"experience", factor:"학업", needs:["subject"],
    text:"{subject} 수업에서 다룬 내용을 다른 과목에서 다시 만난 적이 있나요?",
    purpose:"과목 사이의 연결을 스스로 발견했는지 확인합니다.",
    tails:["두 과목에서 같은 내용을 다루는 방식은 어떻게 달랐나요?","어느 쪽 설명이 더 이해하기 쉬웠고, 이유는 무엇인가요?"] },
  { id:"st-e1-04", area:["seteuk"], intent:"extend", depth:1, kind:"experience", factor:"학업", needs:["book"],
    text:"{book|을} 읽은 뒤 이어서 읽은 책이나 찾아본 자료가 있나요?",
    purpose:"독서가 후속 학습으로 이어졌는지 확인합니다.",
    tails:["그 자료를 고른 이유는 무엇인가요?","두 자료의 관점은 어떻게 달랐나요?"] },
  // 확장·가정 · 깊이 2
  { id:"st-e2-01", area:["seteuk"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic|을} 이어서 탐구한다면 어떤 질문을 세우겠습니까?",
    purpose:"탐구를 스스로 확장하고 설계하는 능력을 확인합니다.",
    tails:["그 질문을 확인할 방법은 무엇인가요?","예상되는 결과와 그렇게 예상하는 이유는 무엇인가요?"] },
  { id:"st-e2-02", area:["seteuk"], intent:"extend", depth:2, kind:"opinion", factor:"진로", needs:["subject"],
    text:"{subject} 과목에서 배운 내용이 지원 전공과 어떻게 이어지는지 말해 주세요.",
    purpose:"이수 과목과 전공의 관계를 이해하고 있는지 확인합니다.",
    tails:["전공 공부에서 이 과목의 어느 단원이 가장 쓰일 것 같나요?","이 과목만으로는 부족한 부분은 무엇이라고 생각하나요?"] },
  { id:"st-e2-03", area:["seteuk"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic|과} 관련해 최근에 접한 기사나 사례가 있다면 소개하고, 본인의 탐구와 이어 보세요.",
    purpose:"교과 탐구를 현실의 문제와 연결해 보는지 확인합니다.",
    tails:["그 사례에서 본인의 탐구로 설명되는 부분은 어디인가요?","설명되지 않는 부분은 무엇인가요?"] },
  { id:"st-e2-04", area:["seteuk"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:[],
    text:"이 탐구의 결과를 실제로 쓸 수 있는 곳이 있다면 어디일까요?",
    purpose:"탐구 결과의 쓰임과 의미를 넓혀 생각하는지 봅니다.",
    tails:["실제로 쓰려면 무엇이 더 확인되어야 하나요?","쓰였을 때 생길 수 있는 문제는 무엇인가요?"] },
  { id:"st-e2-05", area:["seteuk"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:["result"],
    text:"{result|을} 바탕으로 다음에 확인해 보고 싶은 것은 무엇인가요?",
    purpose:"결과에서 새로운 질문을 끌어내는지 확인합니다.",
    tails:["그것을 확인하려면 어떤 자료나 실험이 필요한가요?","예상과 다른 결과가 나온다면 어떻게 해석하겠습니까?"] },
  // 확장·가정 · 깊이 3
  { id:"st-e3-01", area:["seteuk"], intent:"extend", depth:3, kind:"concept", factor:"학업", needs:["topic"],
    text:"{topic|을} 다룬 탐구에서 조건 하나를 바꾼다면 무엇을 바꾸고, 결과가 어떻게 달라질 것으로 예상하나요?",
    purpose:"조건이 달라진 상황에서 근거 있게 추론하는지 봅니다.",
    tails:["그렇게 예상하는 근거는 무엇인가요?","예상이 맞는지 확인하려면 무엇을 측정하거나 조사해야 하나요?"] },
  { id:"st-e3-02", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"본인의 결론과 반대되는 입장에서 {topic|을} 본다면 어떤 주장을 할 수 있을까요?",
    purpose:"자신과 다른 관점에서 문제를 볼 수 있는지 확인합니다.",
    tails:["그 주장에서 가장 강한 근거는 무엇인가요?","그 근거에 본인은 어떻게 답하겠습니까?"] },
  { id:"st-e3-03", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["result"],
    text:"{result|과} 반대되는 자료가 제시된다면 어떻게 판단하겠습니까?",
    purpose:"상충하는 증거를 평가하는 기준이 있는지 확인합니다.",
    tails:["어느 쪽 자료를 더 믿을지 정하는 기준은 무엇인가요?","두 자료가 모두 맞을 수 있는 경우는 없을까요?"] },
  { id:"st-e3-04", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic|을} 다루며 쓴 접근을 전혀 다른 분야의 문제에 적용한다면 어떤 문제에 써 보겠습니까?",
    purpose:"탐구 방법을 다른 분야로 옮겨 적용하는 사고를 봅니다.",
    tails:["그 문제와 원래 주제의 공통점은 무엇인가요?","적용할 때 달라져야 하는 부분은 무엇인가요?"] },
  { id:"st-e3-05", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"비슷한 탐구를 한 친구가 정반대 결론을 냈다고 합시다. 어느 쪽이 맞는지 어떻게 가려내겠습니까?",
    purpose:"유사한 상황에서 증거를 모으고 비교·평가하는 능력을 봅니다.",
    tails:["두 탐구에서 가장 먼저 비교해 볼 조건은 무엇인가요?","본인의 결론이 틀린 것으로 드러나면 어떻게 하겠습니까?"] },
  { id:"st-e3-06", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"이 탐구의 결론을 일반화하기 어렵다는 지적을 받는다면 어떻게 답하겠습니까?",
    purpose:"비판을 받아들이면서 결론의 범위를 조정할 수 있는지 봅니다.",
    tails:["어느 범위까지는 결론이 맞다고 말할 수 있나요?","범위를 넓히려면 무엇을 더 해야 하나요?"] },
  { id:"st-e3-07", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["concept"],
    text:"{concept|을} 활용한 기술이나 제도에서 생길 수 있는 문제는 무엇이라고 생각하나요?",
    purpose:"개념을 사회적 맥락으로 넓혀 비판적으로 보는지 확인합니다.",
    tails:["그 문제를 줄이는 방법은 무엇인가요?","그 방법으로 새로 생기는 부담은 누가 지게 되나요?"] },
  { id:"st-e3-08", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["book"],
    text:"{book}의 주장을 지금 우리 사회의 문제 하나에 적용해 보세요.",
    purpose:"독서 내용을 현실 문제에 적용해 생각하는지 확인합니다.",
    tails:["저자의 주장이 그대로 통하지 않는 부분은 무엇인가요?","그 부분을 보완하려면 어떤 관점이 더 필요한가요?"] },
  { id:"st-e3-09", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"후배가 {topic|을} 이어서 탐구한다면 무엇부터 고치라고 조언하겠습니까?",
    purpose:"자신의 탐구를 객관적으로 보고 개선 우선순위를 정하는지 봅니다.",
    tails:["그 점이 가장 큰 문제였다고 보는 이유는 무엇인가요?","그 조언을 따르면 새로 생길 어려움은 무엇인가요?"] },

  /* ════════ 자율·자치활동 (jayul) ════════ */
  // 선택·동기 · 깊이 1
  { id:"jy-m1-01", area:["jayul"], intent:"motive", depth:1, kind:"experience", factor:"공동체", needs:["topic"],
    text:"자율활동에서 {topic} 활동을 하게 된 계기는 무엇인가요?",
    purpose:"활동의 출발점과 본인의 주도성을 확인합니다.",
    tails:["누가 먼저 제안했나요?","처음 제안과 실제 활동은 어떻게 달라졌나요?"] },
  { id:"jy-m1-02", area:["jayul"], intent:"motive", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡게 된 과정을 말해 주세요. 스스로 나선 것인가요?",
    purpose:"역할을 맡은 경위와 책임을 지려는 태도를 확인합니다.",
    tails:["맡기 전에 걱정한 점은 무엇이었나요?","맡은 뒤 그 걱정은 어떻게 되었나요?"] },
  { id:"jy-m1-03", area:["jayul"], intent:"motive", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"이 활동에는 스스로 참여했나요, 학급 전체가 함께 한 활동인가요?",
    purpose:"단체 활동 속에서 본인의 참여가 능동적이었는지 확인합니다.",
    tails:["전체가 함께 한 활동이라면 그 안에서 본인이 따로 한 일은 무엇인가요?","참여하면서 처음 가진 기대는 무엇이었나요?"] },
  // 선택·동기 · 깊이 2
  { id:"jy-m2-01", area:["jayul"], intent:"motive", depth:2, kind:"opinion", factor:"공동체", needs:["topic"],
    text:"{topic} 활동이 학급이나 학교에 왜 필요하다고 판단했나요?",
    purpose:"공동체의 문제를 스스로 발견하고 판단했는지 확인합니다.",
    tails:["그 필요를 어떻게 확인했나요?","필요 없다고 본 친구들은 어떻게 설득했나요?"] },
  { id:"jy-m2-02", area:["jayul"], intent:"motive", depth:2, kind:"opinion", factor:"공동체", needs:["role"],
    text:"{role|을} 맡아 가장 먼저 하려고 한 일은 무엇이었고, 이유는 무엇인가요?",
    purpose:"역할에 대한 목표 의식과 우선순위 판단을 확인합니다.",
    tails:["그 일은 계획대로 되었나요?","우선순위를 바꿔야 했던 순간이 있었다면 언제였나요?"] },
  { id:"jy-m2-03", area:["jayul"], intent:"motive", depth:2, kind:"opinion", factor:"공동체", needs:[],
    text:"여러 활동 가운데 이 활동에 시간을 더 쓰기로 한 이유는 무엇인가요?",
    purpose:"자신의 관심과 우선순위를 근거 있게 판단했는지 확인합니다.",
    tails:["그 선택 때문에 미루거나 포기한 것은 무엇인가요?","결과적으로 그 판단이 옳았다고 보는 근거는 무엇인가요?"] },
  // 선택·동기 · 깊이 3
  { id:"jy-m3-01", area:["jayul"], intent:"motive", depth:3, kind:"opinion", factor:"공동체", needs:["topic"],
    text:"{topic} 활동을 다시 기획한다면 목표를 그대로 두겠습니까, 바꾸겠습니까?",
    purpose:"활동의 목표를 돌아보고 다시 평가할 수 있는지 봅니다.",
    tails:["그렇게 판단하게 된 경험은 무엇인가요?","목표가 바뀌면 참여하는 사람들의 역할은 어떻게 달라지나요?"] },
  { id:"jy-m3-02", area:["jayul"], intent:"motive", depth:3, kind:"opinion", factor:"공동체", needs:[],
    text:"이 활동이 일부 학생만의 활동이었다는 지적을 받는다면 어떻게 답하겠습니까?",
    purpose:"활동의 한계를 인정하고 공동체 전체를 생각하는지 확인합니다.",
    tails:["참여하지 않은 학생들의 이유는 무엇이었다고 보나요?","더 많은 학생이 참여하게 하려면 무엇을 바꿔야 했나요?"] },
  // 과정·역할 · 깊이 1
  { id:"jy-p1-01", area:["jayul"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:["topic"],
    text:"{topic} 활동을 진행할 때 본인이 직접 맡아 한 일을 구체적으로 말해 주세요.",
    purpose:"단체 활동에서 본인의 실제 역할과 기여를 확인합니다.",
    tails:["그 일에 든 시간과 횟수는 어느 정도였나요?","함께 한 친구들은 각각 무엇을 맡았나요?"] },
  { id:"jy-p1-02", area:["jayul"], intent:"process", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role} 역할을 하면서 정기적으로 한 일은 무엇이었나요?",
    purpose:"기록된 역할을 꾸준히 수행했는지 확인합니다.",
    tails:["그 가운데 손이 가장 많이 간 일은 무엇인가요?","그 일을 하면서 누구와 가장 자주 상의했나요?"] },
  { id:"jy-p1-03", area:["jayul"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"이 활동에 몇 명이 참여했고, 본인의 기여는 어느 정도였다고 생각하나요?",
    purpose:"기여도를 과장 없이 스스로 평가하는지 확인합니다.",
    tails:["그렇게 평가하는 근거는 무엇인가요?","다른 친구의 기여 가운데 인상 깊었던 것은 무엇인가요?"] },
  // 과정·역할 · 깊이 2
  { id:"jy-p2-01", area:["jayul"], intent:"process", depth:2, kind:"experience", factor:"소통", needs:["topic"],
    text:"{topic} 활동을 준비하면서 의견이 가장 크게 갈린 지점은 무엇이었고, 어떻게 결론을 냈나요?",
    purpose:"의견 차이를 조정하는 과정과 소통 방식을 확인합니다.",
    tails:["본인은 어느 쪽 의견이었나요?","결론에 동의하지 않은 친구는 그 뒤 어떻게 참여했나요?"] },
  { id:"jy-p2-02", area:["jayul"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡는 동안 협조하지 않는 친구가 있었다면 어떻게 대했나요?",
    purpose:"갈등 상황에서 상대를 대하는 태도를 확인합니다.",
    tails:["그 친구의 입장은 무엇이었나요?","본인의 대응 가운데 아쉬운 점은 무엇인가요?"] },
  { id:"jy-p2-03", area:["jayul"], intent:"process", depth:2, kind:"experience", factor:"소통", needs:[],
    text:"이 활동에서 친구들의 의견을 모을 때 어떤 방법을 썼나요?",
    purpose:"의견을 듣고 모으는 구체적인 방법이 있었는지 확인합니다.",
    tails:["의견을 잘 내지 않는 친구들의 생각은 어떻게 들었나요?","모은 의견 가운데 반영하지 못한 것은 어떻게 처리했나요?"] },
  { id:"jy-p2-04", area:["jayul"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:["topic"],
    text:"{topic} 활동을 진행하다가 계획대로 되지 않은 일은 무엇이었고, 어떻게 조정했나요?",
    purpose:"예상하지 못한 상황에서의 대처와 책임감을 확인합니다.",
    tails:["조정할 때 누구와 상의했나요?","조정한 뒤에도 남은 문제는 무엇이었나요?"] },
  // 과정·역할 · 깊이 3
  { id:"jy-p3-01", area:["jayul"], intent:"process", depth:3, kind:"opinion", factor:"공동체", needs:["topic"],
    text:"{topic} 활동을 추진할 때 다수가 본인의 결정에 반대했다면 어떻게 하겠습니까?",
    purpose:"다수 의견과 자신의 판단이 부딪힐 때의 기준을 봅니다.",
    tails:["다수 의견이 틀렸다고 확신할 때에도 따르겠습니까?","그 판단의 기준은 무엇인가요?"] },
  { id:"jy-p3-02", area:["jayul"], intent:"process", depth:3, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡은 사람에게 필요한 것 가운데 본인에게 부족했던 것은 무엇인가요?",
    purpose:"역할 수행을 정직하게 돌아보는지 확인합니다.",
    tails:["그 부족함이 드러난 장면을 말해 주세요.","그 뒤에 어떻게 보완했나요?"] },
  { id:"jy-p3-03", area:["jayul"], intent:"process", depth:3, kind:"opinion", factor:"공동체", needs:[],
    text:"이 활동을 인원이 두 배인 집단에서 한다면 진행 방식을 어떻게 바꾸겠습니까?",
    purpose:"조건이 달라졌을 때 운영 방식을 다시 설계하는 능력을 봅니다.",
    tails:["가장 먼저 생길 문제는 무엇일까요?","그 문제를 줄이려면 어떤 장치가 필요한가요?"] },
  // 개념·원리 · 깊이 1
  { id:"jy-c1-01", area:["jayul"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["concept"],
    text:"자율활동 기록에 {concept|이라는} 말이 나옵니다. 무슨 뜻인지 설명해 보세요.",
    purpose:"기록에 쓰인 용어를 이해하고 있는지 확인합니다.",
    tails:["이 말을 어디에서 처음 접했나요?","활동에서 이 개념은 어떻게 쓰였나요?"] },
  { id:"jy-c1-02", area:["jayul"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:[],
    text:"이 활동에서 새로 알게 된 용어나 개념을 하나 골라 뜻을 말해 주세요.",
    purpose:"활동에서 실제로 배운 내용이 있는지 확인합니다.",
    tails:["활동 전에는 그 개념을 어떻게 이해하고 있었나요?","그 개념이 쓰이는 다른 사례를 들어 보세요."] },
  // 개념·원리 · 깊이 2
  { id:"jy-c2-01", area:["jayul"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["topic"],
    text:"{topic|과} 관련해 꼭 알아야 하는 배경 지식을 하나 설명해 보세요.",
    purpose:"활동의 바탕이 되는 지식을 갖추었는지 확인합니다.",
    tails:["그 지식은 어디에서 확인했나요?","그 지식을 모르는 친구에게는 어떻게 전달했나요?"] },
  { id:"jy-c2-02", area:["jayul"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|이} 이 활동의 주제와 어떻게 연결되는지 설명해 보세요.",
    purpose:"개념과 활동의 관계를 이해하고 있는지 확인합니다.",
    tails:["그 연결을 뒷받침하는 사례나 자료는 무엇인가요?","연결이 약하다고 느낀 부분은 없나요?"] },
  { id:"jy-c2-03", area:["jayul"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:[],
    text:"이 활동에서 다룬 문제의 원인을 본인이 이해한 대로 설명해 보세요.",
    purpose:"문제의 원인을 구조적으로 이해했는지 확인합니다.",
    tails:["그 원인 가운데 가장 중요한 것은 무엇이라고 보나요?","원인을 다르게 설명하는 입장이 있다면 무엇인가요?"] },
  // 개념·원리 · 깊이 3
  { id:"jy-c3-01", area:["jayul"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|을} 학교 밖 사회 문제에 적용한다면 어떤 사례가 있을까요?",
    purpose:"개념을 더 넓은 맥락에 적용할 수 있는지 봅니다.",
    tails:["학교 안의 경우와 무엇이 다른가요?","그 차이 때문에 해결 방법은 어떻게 달라지나요?"] },
  { id:"jy-c3-02", area:["jayul"], intent:"concept", depth:3, kind:"opinion", factor:"공동체", needs:["topic"],
    text:"{topic} 활동에서 내세운 해결책이 통하지 않는 경우가 있다면 어떤 경우일까요?",
    purpose:"자신이 낸 해결책의 한계를 알고 있는지 확인합니다.",
    tails:["그 경우에는 어떤 대안이 있나요?","그 대안에 드는 부담은 누가 지게 되나요?"] },
  { id:"jy-c3-03", area:["jayul"], intent:"concept", depth:3, kind:"opinion", factor:"공동체", needs:[],
    text:"이 활동에서 옳다고 본 원칙이 다른 가치와 부딪히는 경우를 예로 들어 보세요.",
    purpose:"가치가 충돌하는 상황에서 판단하는 기준을 봅니다.",
    tails:["그때는 무엇을 우선하겠습니까?","우선순위를 정한 기준은 무엇인가요?"] },
  // 배움·변화 · 깊이 1
  { id:"jy-g1-01", area:["jayul"], intent:"growth", depth:1, kind:"experience", factor:"공동체", needs:["topic"],
    text:"{topic} 활동을 마치고 가장 크게 느낀 점은 무엇인가요?",
    purpose:"활동에서 얻은 배움이 구체적인지 확인합니다.",
    tails:["그렇게 느끼게 된 장면을 말해 주세요.","활동 전에는 그 점을 어떻게 생각했나요?"] },
  { id:"jy-g1-02", area:["jayul"], intent:"growth", depth:1, kind:"experience", factor:"공동체", needs:[],
    text:"이 활동에서 가장 보람 있었던 순간은 언제였나요?",
    purpose:"활동에 대한 몰입과 가치 인식을 확인합니다.",
    tails:["그 순간이 보람 있었던 이유는 무엇인가요?","반대로 가장 힘들었던 순간은 언제였나요?"] },
  // 배움·변화 · 깊이 2
  { id:"jy-g2-01", area:["jayul"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡기 전과 후에 친구들을 대하는 방식이 어떻게 달라졌나요?",
    purpose:"역할 경험이 태도의 변화로 이어졌는지 확인합니다.",
    tails:["달라진 것을 보여 주는 사례를 말해 주세요.","예전 방식에는 어떤 문제가 있었나요?"] },
  { id:"jy-g2-02", area:["jayul"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:["topic"],
    text:"{topic} 활동을 하면서 공동체에 대한 생각이 달라진 부분이 있나요?",
    purpose:"경험을 통해 가치관이 자랐는지 확인합니다.",
    tails:["생각을 바꾼 계기는 무엇이었나요?","그 뒤 행동에서 달라진 것은 무엇인가요?"] },
  { id:"jy-g2-03", area:["jayul"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"이 활동에서 친구에게 배운 점이 있다면 무엇인가요?",
    purpose:"다른 사람에게서 배우려는 열린 태도를 확인합니다.",
    tails:["그 친구의 어떤 행동에서 배웠나요?","배운 점을 실제로 따라 해 본 적이 있나요?"] },
  // 배움·변화 · 깊이 3
  { id:"jy-g3-01", area:["jayul"], intent:"growth", depth:3, kind:"opinion", factor:"공동체", needs:["topic"],
    text:"{topic} 활동에서 얻은 경험을 대학의 조별 과제나 학생 자치에 어떻게 쓰겠습니까?",
    purpose:"경험을 새로운 환경에 옮겨 적용할 수 있는지 봅니다.",
    tails:["대학은 구성원이 다릅니다. 무엇이 달라져야 할까요?","그대로 쓰기 어려운 부분은 무엇인가요?"] },
  { id:"jy-g3-02", area:["jayul"], intent:"growth", depth:3, kind:"experience", factor:"공동체", needs:[],
    text:"이 활동에서 드러난 본인의 약점은 무엇이고, 지금은 어떻게 달라졌나요?",
    purpose:"약점을 인식하고 고쳐 온 과정을 확인합니다.",
    tails:["달라졌다고 말할 수 있는 근거는 무엇인가요?","아직 남아 있는 부분은 어떻게 하려고 하나요?"] },
  // 확장·가정 · 깊이 1
  { id:"jy-e1-01", area:["jayul"], intent:"extend", depth:1, kind:"experience", factor:"공동체", needs:["topic"],
    text:"{topic} 활동은 한 번으로 끝났나요, 그 뒤에도 이어졌나요?",
    purpose:"활동의 지속성과 실제 영향을 확인합니다.",
    tails:["이어졌다면 누가 이어 갔나요?","이어지지 않았다면 이유는 무엇이라고 보나요?"] },
  { id:"jy-e1-02", area:["jayul"], intent:"extend", depth:1, kind:"experience", factor:"공동체", needs:[],
    text:"이 활동이 끝난 뒤 학급이나 학교에 실제로 달라진 것이 있나요?",
    purpose:"활동이 공동체에 남긴 결과를 확인합니다.",
    tails:["그 변화는 어떻게 확인했나요?","변화가 오래가지 않았다면 이유는 무엇일까요?"] },
  // 확장·가정 · 깊이 2
  { id:"jy-e2-01", area:["jayul"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic} 활동의 효과를 확인하려면 무엇을 조사하거나 측정해야 할까요?",
    purpose:"활동의 결과를 근거로 평가하는 사고를 확인합니다.",
    tails:["그 방법의 약점은 무엇인가요?","효과가 없었다는 결과가 나오면 어떻게 하겠습니까?"] },
  { id:"jy-e2-02", area:["jayul"], intent:"extend", depth:2, kind:"opinion", factor:"공동체", needs:[],
    text:"이 활동을 다음 학년 후배들이 이어 간다면 무엇을 남겨 주겠습니까?",
    purpose:"경험을 정리해 다른 사람에게 전하는 능력을 봅니다.",
    tails:["그 가운데 가장 중요한 것 하나는 무엇인가요?","후배들이 같은 실수를 하지 않으려면 무엇을 알아야 하나요?"] },
  { id:"jy-e2-03", area:["jayul"], intent:"extend", depth:2, kind:"opinion", factor:"진로", needs:["role"],
    text:"{role} 경험이 지원한 전공 공부나 대학 생활과 어떻게 이어진다고 생각하나요?",
    purpose:"공동체 경험과 진로를 연결해 생각하는지 확인합니다.",
    tails:["전공 공부에서 그 경험이 쓰일 장면을 하나 예로 들어 보세요.","그 경험만으로는 부족한 부분은 무엇인가요?"] },
  // 확장·가정 · 깊이 3
  { id:"jy-e3-01", area:["jayul"], intent:"extend", depth:3, kind:"opinion", factor:"공동체", needs:["topic"],
    text:"{topic} 활동을 예산과 시간이 절반인 조건에서 해야 한다면 무엇을 남기고 무엇을 빼겠습니까?",
    purpose:"제약이 생겼을 때 핵심을 가려내는 판단력을 봅니다.",
    tails:["남긴 것이 핵심이라고 본 이유는 무엇인가요?","빠진 부분 때문에 생길 문제는 어떻게 줄이겠습니까?"] },
  { id:"jy-e3-02", area:["jayul"], intent:"extend", depth:3, kind:"opinion", factor:"소통", needs:[],
    text:"이 활동의 취지에 반대하는 학생의 입장에서 반대 이유를 말해 보고, 그에 답해 보세요.",
    purpose:"반대 입장을 이해하고 근거로 답하는 능력을 봅니다.",
    tails:["그 반대 의견에서 받아들일 부분은 무엇인가요?","받아들이면 활동이 어떻게 달라지나요?"] },
  { id:"jy-e3-03", area:["jayul"], intent:"extend", depth:3, kind:"opinion", factor:"공동체", needs:["role"],
    text:"{role|을} 맡아 내린 결정이 틀렸다는 것이 뒤늦게 드러났다면 어떻게 하겠습니까?",
    purpose:"잘못을 인정하고 책임지는 태도를 확인합니다.",
    tails:["구성원에게는 어떻게 알리겠습니까?","같은 일이 반복되지 않게 무엇을 바꾸겠습니까?"] },

  /* ════════ 동아리활동 (dongari) ════════ */
  // 선택·동기 · 깊이 1
  { id:"da-m1-01", area:["dongari"], intent:"motive", depth:1, kind:"opinion", factor:"진로", needs:[],
    text:"이 동아리에 들어간 계기는 무엇인가요?",
    purpose:"동아리 선택에 본인의 관심이 반영되었는지 확인합니다.",
    tails:["들어가기 전 기대한 것과 실제는 어떻게 달랐나요?","다른 동아리도 고민했나요?"] },
  { id:"da-m1-02", area:["dongari"], intent:"motive", depth:1, kind:"experience", factor:"진로", needs:["topic"],
    text:"동아리에서 {topic} 활동을 하자는 제안은 누가 했고, 본인은 어떤 의견을 냈나요?",
    purpose:"활동 주제가 정해진 과정과 본인의 관여를 확인합니다.",
    tails:["본인의 의견 가운데 실제로 반영된 것은 무엇인가요?","처음 계획에서 달라진 부분은 무엇인가요?"] },
  { id:"da-m1-03", area:["dongari"], intent:"motive", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"동아리에서 {role|을} 맡게 된 과정을 말해 주세요.",
    purpose:"역할을 맡은 경위와 부원들의 신뢰를 확인합니다.",
    tails:["부원들이 본인에게 기대한 것은 무엇이었다고 생각하나요?","그 기대에 얼마나 맞게 했다고 보나요?"] },
  // 선택·동기 · 깊이 2
  { id:"da-m2-01", area:["dongari"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:[],
    text:"여러 동아리 가운데 이 동아리를 고른 이유는 무엇이고, 지원 전공과는 어떤 관련이 있나요?",
    purpose:"동아리 선택과 진로 관심의 연결을 확인합니다.",
    tails:["전공과 관련이 없었다면 그래도 골랐을까요?","동아리 활동이 진로 결정에 준 영향은 무엇인가요?"] },
  { id:"da-m2-02", area:["dongari"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:["topic"],
    text:"동아리 활동 주제로 {topic|을} 정할 때 본인은 어떤 근거로 찬성하거나 제안했나요?",
    purpose:"주제 선정에 본인의 판단이 들어갔는지 확인합니다.",
    tails:["다른 후보 주제는 무엇이었나요?","부원들을 설득한 방법은 무엇이었나요?"] },
  { id:"da-m2-03", area:["dongari"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:[],
    text:"같은 동아리를 계속했나요, 바꿨나요? 그렇게 한 이유를 말해 주세요.",
    purpose:"관심의 지속성 또는 변화의 이유를 확인합니다.",
    tails:["그 결정으로 얻은 것은 무엇인가요?","그 결정으로 놓친 것이 있다면 무엇인가요?"] },
  // 선택·동기 · 깊이 3
  { id:"da-m3-01", area:["dongari"], intent:"motive", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"이 동아리 대신 다른 동아리를 했다면 지금 진로 생각이 달라졌을까요?",
    purpose:"진로 결정에서 동아리 경험이 차지하는 무게를 확인합니다.",
    tails:["그렇게 보는 이유는 무엇인가요?","동아리 밖에서 진로에 영향을 준 경험은 무엇인가요?"] },
  { id:"da-m3-02", area:["dongari"], intent:"motive", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic} 활동이 동아리의 성격에 맞았는지 지금 평가한다면 어떻습니까?",
    purpose:"활동 선택을 한 발 떨어져 평가할 수 있는지 봅니다.",
    tails:["그렇게 평가하는 기준은 무엇인가요?","더 잘 맞는 활동을 하나 제안한다면 무엇인가요?"] },
  // 과정·역할 · 깊이 1
  { id:"da-p1-01", area:["dongari"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:["topic"],
    text:"동아리에서 {topic|을} 다룰 때 본인이 맡은 부분은 무엇이었나요?",
    purpose:"공동 활동에서 본인의 실제 역할을 확인합니다.",
    tails:["그 부분을 맡게 된 이유는 무엇인가요?","맡은 부분의 결과물은 무엇이었나요?"] },
  { id:"da-p1-02", area:["dongari"], intent:"process", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"동아리에서 {role|을} 맡았다고 되어 있는데, 부원은 몇 명이었고 무엇을 책임졌나요?",
    purpose:"기록된 직책의 실제 책임 범위를 확인합니다.",
    tails:["한 학기 동안 가장 자주 한 일은 무엇인가요?","부원들은 본인의 역할 수행을 어떻게 평가했을 것 같나요?"] },
  { id:"da-p1-03", area:["dongari"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"동아리 활동은 주로 어떤 방식으로 진행되었고, 본인은 얼마나 자주 참여했나요?",
    purpose:"동아리 참여의 성실성과 꾸준함을 확인합니다.",
    tails:["가장 꾸준히 한 활동은 무엇인가요?","참여하지 못한 때가 있었다면 어떻게 보완했나요?"] },
  // 과정·역할 · 깊이 2
  { id:"da-p2-01", area:["dongari"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:["topic"],
    text:"동아리에서 {topic} 활동을 진행할 때 역할은 어떻게 나누었고, 그 기준은 무엇이었나요?",
    purpose:"협업 방식과 역할 분담의 합리성을 확인합니다.",
    tails:["역할 분담에 불만이 있는 부원은 없었나요?","맡은 일을 다 하지 못한 부원이 있었다면 어떻게 했나요?"] },
  { id:"da-p2-02", area:["dongari"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"동아리에서 {topic} 활동을 하면서 실패하거나 다시 한 과정이 있었나요? 원인을 어떻게 찾았나요?",
    purpose:"시행착오를 분석하고 고쳐 가는 과정을 확인합니다.",
    tails:["원인에 대해 부원끼리 의견이 달랐던 적은 없나요?","다시 했을 때 무엇을 바꾸었나요?"] },
  { id:"da-p2-03", area:["dongari"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"동아리에서 의견이 부딪혔던 경험을 말해 주세요. 본인은 어떻게 했나요?",
    purpose:"갈등 상황에서의 태도와 해결 방식을 확인합니다.",
    tails:["상대의 주장은 무엇이었나요?","그 일 뒤에 그 부원과의 관계는 어떻게 되었나요?"] },
  { id:"da-p2-04", area:["dongari"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡아 부원들의 참여를 끌어내기 위해 쓴 방법은 무엇인가요?",
    purpose:"리더로서의 구체적인 행동을 확인합니다.",
    tails:["효과가 없었던 방법도 있었나요?","참여가 적은 부원에게는 따로 어떻게 했나요?"] },
  // 과정·역할 · 깊이 3
  { id:"da-p3-01", area:["dongari"], intent:"process", depth:3, kind:"opinion", factor:"공동체", needs:["topic"],
    text:"동아리의 {topic} 활동을 혼자 했다면 결과가 어떻게 달라졌을까요?",
    purpose:"협업의 가치와 한계를 스스로 평가하는지 봅니다.",
    tails:["협업으로 더 좋아진 부분은 무엇인가요?","협업 때문에 오히려 어려웠던 부분은 무엇인가요?"] },
  { id:"da-p3-02", area:["dongari"], intent:"process", depth:3, kind:"opinion", factor:"공동체", needs:[],
    text:"이 동아리 활동의 진행 방식에서 고쳐야 할 점 하나를 꼽고, 개선안을 말해 주세요.",
    purpose:"활동을 비판적으로 돌아보고 대안을 내는지 확인합니다.",
    tails:["그 개선안에 반대할 부원이 있다면 이유는 무엇일까요?","그래도 고쳐야 한다고 보는 이유는 무엇인가요?"] },
  { id:"da-p3-03", area:["dongari"], intent:"process", depth:3, kind:"opinion", factor:"공동체", needs:["role"],
    text:"{role|을} 맡은 동안 내린 결정 가운데 지금이라면 다르게 할 결정은 무엇인가요?",
    purpose:"자신의 결정을 돌아보고 배우는지 확인합니다.",
    tails:["그때는 왜 그렇게 결정했나요?","다르게 했다면 결과가 어떻게 달라졌을까요?"] },
  // 개념·원리 · 깊이 1
  { id:"da-c1-01", area:["dongari"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["concept"],
    text:"동아리 기록에 {concept|이} 나옵니다. 무엇인지 간단히 설명해 보세요.",
    purpose:"동아리 활동에 쓰인 개념을 이해하고 있는지 확인합니다.",
    tails:["동아리에서 이 개념을 어떻게 공부했나요?","설명 가운데 본인이 직접 확인해 본 부분은 무엇인가요?"] },
  { id:"da-c1-02", area:["dongari"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:[],
    text:"이 동아리 활동에 쓰인 핵심 지식이나 기술을 하나 꼽아 설명해 보세요.",
    purpose:"활동의 바탕이 되는 지식을 갖추었는지 확인합니다.",
    tails:["그것은 수업에서 배운 것인가요, 따로 익힌 것인가요?","익히는 데 가장 어려웠던 부분은 무엇인가요?"] },
  // 개념·원리 · 깊이 2
  { id:"da-c2-01", area:["dongari"], intent:"concept", depth:2, kind:"concept", factor:"소통", needs:["topic"],
    text:"동아리에서 다룬 {topic|을} 이 분야를 모르는 사람에게 원리부터 설명해 보세요.",
    purpose:"내용을 이해한 깊이와 전달력을 함께 확인합니다.",
    tails:["방금 설명에서 생략한 부분은 무엇인가요?","그 원리를 확인할 수 있는 간단한 방법이 있나요?"] },
  { id:"da-c2-02", area:["dongari"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|이} 동아리 활동의 결과물에 어떻게 적용되었는지 설명해 보세요.",
    purpose:"개념을 실제 활동에 적용했는지 확인합니다.",
    tails:["적용하면서 이론과 실제가 달랐던 점은 무엇인가요?","그 차이는 왜 생겼다고 보나요?"] },
  { id:"da-c2-03", area:["dongari"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:[],
    text:"동아리에서 만든 결과물이나 결론이 어떤 원리로 나온 것인지 설명해 보세요.",
    purpose:"결과를 원리로 설명할 수 있는지 확인합니다.",
    tails:["그 원리를 수업 내용과 연결하면 어느 단원인가요?","원리와 맞지 않게 나온 부분은 없었나요?"] },
  // 개념·원리 · 깊이 3
  { id:"da-c3-01", area:["dongari"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|을} 동아리에서 다룬 것보다 큰 규모나 실제 현장에 적용하면 어떤 문제가 생길까요?",
    purpose:"조건이 달라질 때 생기는 문제를 예측하는지 봅니다.",
    tails:["그 문제를 줄이는 방법은 무엇인가요?","그 방법을 쓰려면 무엇을 더 배워야 하나요?"] },
  { id:"da-c3-02", area:["dongari"], intent:"concept", depth:3, kind:"concept", factor:"학업", needs:["topic"],
    text:"{topic} 활동에서 실패한 시도가 있었다면, 왜 실패했는지 원리로 설명해 보세요.",
    purpose:"실패의 원인을 개념 수준에서 분석하는지 확인합니다.",
    tails:["그 설명이 맞는지 어떻게 확인할 수 있나요?","같은 실패를 피하려면 설계를 어떻게 바꿔야 하나요?"] },
  { id:"da-c3-03", area:["dongari"], intent:"concept", depth:3, kind:"concept", factor:"진로", needs:[],
    text:"동아리에서 다룬 내용이 전공 분야에서는 어떻게 응용되는지 아는 대로 말해 보세요.",
    purpose:"동아리 활동을 전공 분야의 지식과 연결하는지 봅니다.",
    tails:["그 응용에서 고등학교 수준과 가장 크게 다른 점은 무엇일까요?","그 차이를 메우려면 대학에서 무엇을 배워야 하나요?"] },
  // 배움·변화 · 깊이 1
  { id:"da-g1-01", area:["dongari"], intent:"growth", depth:1, kind:"experience", factor:"학업", needs:["topic"],
    text:"동아리에서 {topic} 활동을 하고 나서 할 수 있게 된 것은 무엇인가요?",
    purpose:"활동으로 얻은 능력이 구체적인지 확인합니다.",
    tails:["처음에는 어느 정도 수준이었나요?","그 능력을 다른 곳에 써 본 적이 있나요?"] },
  { id:"da-g1-02", area:["dongari"], intent:"growth", depth:1, kind:"experience", factor:"진로", needs:[],
    text:"동아리 활동 가운데 가장 기억에 남는 것을 하나 꼽고, 이유를 말해 주세요.",
    purpose:"동아리 경험의 깊이와 의미 부여를 확인합니다.",
    tails:["그 활동에서 본인이 한 일은 무엇인가요?","그 활동이 없었다면 무엇을 배우지 못했을까요?"] },
  // 배움·변화 · 깊이 2
  { id:"da-g2-01", area:["dongari"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"동아리에서 여러 사람과 함께 하면서 협업에 대해 새로 알게 된 점은 무엇인가요?",
    purpose:"협업 경험에서 얻은 배움을 확인합니다.",
    tails:["그 점을 알게 된 사건을 말해 주세요.","그 뒤 모둠 활동에서 실제로 달리 행동한 것이 있나요?"] },
  { id:"da-g2-02", area:["dongari"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 하면서 본인의 장점과 단점 가운데 새로 알게 된 것은 무엇인가요?",
    purpose:"역할 경험을 통한 자기 이해를 확인합니다.",
    tails:["단점이 드러난 장면을 말해 주세요.","그 단점을 고치려고 무엇을 했나요?"] },
  { id:"da-g2-03", area:["dongari"], intent:"growth", depth:2, kind:"experience", factor:"진로", needs:["topic"],
    text:"동아리에서 {topic} 활동을 하면서 전공 분야에 대한 생각이 어떻게 달라졌나요?",
    purpose:"활동이 진로 인식의 변화로 이어졌는지 확인합니다.",
    tails:["달라지기 전에는 어떻게 생각했나요?","그 변화가 과목 선택이나 다른 활동에 영향을 주었나요?"] },
  // 배움·변화 · 깊이 3
  { id:"da-g3-01", area:["dongari"], intent:"growth", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"동아리 경험에 비추어 볼 때 대학 공부에서 가장 보완해야 할 점은 무엇인가요?",
    purpose:"자신의 부족함을 알고 계획을 세우는지 확인합니다.",
    tails:["보완하려고 지금 하고 있는 것이 있나요?","대학에서는 어떤 방법으로 보완하겠습니까?"] },
  { id:"da-g3-02", area:["dongari"], intent:"growth", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"동아리의 {topic} 활동에서 익힌 방식이 통하지 않을 상황을 하나 들어 보세요.",
    purpose:"익힌 방법의 적용 범위와 한계를 생각하는지 봅니다.",
    tails:["왜 통하지 않는다고 보나요?","그 상황에서는 어떤 방식이 필요할까요?"] },
  // 확장·가정 · 깊이 1
  { id:"da-e1-01", area:["dongari"], intent:"extend", depth:1, kind:"experience", factor:"학업", needs:[],
    text:"동아리 활동이 수업이나 다른 활동으로 이어진 것이 있나요?",
    purpose:"기록 사이의 연결과 관심의 확장을 확인합니다.",
    tails:["어느 쪽이 먼저였나요?","이어지면서 더 깊어진 내용은 무엇인가요?"] },
  { id:"da-e1-02", area:["dongari"], intent:"extend", depth:1, kind:"experience", factor:"소통", needs:["topic"],
    text:"동아리에서 {topic} 활동을 한 뒤 결과를 발표하거나 나눈 적이 있나요?",
    purpose:"활동 결과를 다른 사람과 나눈 경험을 확인합니다.",
    tails:["듣는 사람들의 반응은 어땠나요?","그 반응을 보고 고친 부분이 있나요?"] },
  // 확장·가정 · 깊이 2
  { id:"da-e2-01", area:["dongari"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:["topic"],
    text:"동아리에서 {topic|을} 한 학기 더 다룬다면 무엇을 추가하겠습니까?",
    purpose:"활동을 스스로 확장해 설계하는 능력을 확인합니다.",
    tails:["그것을 추가하려는 이유는 무엇인가요?","추가하려면 어떤 준비가 필요한가요?"] },
  { id:"da-e2-02", area:["dongari"], intent:"extend", depth:2, kind:"opinion", factor:"진로", needs:[],
    text:"동아리에서 한 활동이 지원 전공의 어떤 공부와 이어진다고 생각하나요?",
    purpose:"동아리 경험과 전공 학업의 연결을 확인합니다.",
    tails:["그 공부를 대학에서 어떻게 시작할 계획인가요?","동아리 활동만으로는 알 수 없었던 전공의 모습은 무엇일까요?"] },
  { id:"da-e2-03", area:["dongari"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:["concept"],
    text:"{concept}에 대해 동아리에서 다 다루지 못한 부분은 무엇이고, 어떻게 더 알아보겠습니까?",
    purpose:"남은 과제를 알고 후속 학습을 계획하는지 확인합니다.",
    tails:["다루지 못한 이유는 무엇이었나요?","더 알아볼 때 가장 먼저 찾아볼 것은 무엇인가요?"] },
  // 확장·가정 · 깊이 3
  { id:"da-e3-01", area:["dongari"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"동아리에서 {topic|을} 다룬 결과를 전문가가 본다면 어떤 점을 지적할 것 같나요?",
    purpose:"자신의 결과물을 높은 기준에서 평가하는지 봅니다.",
    tails:["그 지적에 어떻게 답하겠습니까?","지적을 반영하려면 무엇을 바꿔야 하나요?"] },
  { id:"da-e3-02", area:["dongari"], intent:"extend", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"새 부원이 이 동아리 활동은 진로에 도움이 안 된다고 말한다면 어떻게 답하겠습니까?",
    purpose:"활동의 가치를 근거 있게 설명하는지 확인합니다.",
    tails:["그 말에서 맞는 부분은 무엇인가요?","그렇다면 동아리 활동을 어떻게 바꾸겠습니까?"] },
  { id:"da-e3-03", area:["dongari"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"동아리에서 {topic} 활동을 할 때 쓸 수 있는 도구나 자료가 훨씬 적었다면 어떻게 진행했겠습니까?",
    purpose:"제약 조건에서 대안을 찾는 문제 해결력을 봅니다.",
    tails:["그 조건에서도 꼭 지켜야 하는 것은 무엇인가요?","결과의 질은 어떻게 달라질까요?"] },

  /* ════════ 진로활동 (jinro) ════════ */
  // 선택·동기 · 깊이 1
  { id:"jr-m1-01", area:["jinro"], intent:"motive", depth:1, kind:"opinion", factor:"진로", needs:[],
    text:"지금의 진로를 처음 생각하게 된 계기는 무엇인가요?",
    purpose:"진로 관심의 출발점이 구체적인 경험인지 확인합니다.",
    tails:["그 계기 뒤에 관심이 이어진 활동은 무엇인가요?","그전에는 어떤 진로를 생각했나요?"] },
  { id:"jr-m1-02", area:["jinro"], intent:"motive", depth:1, kind:"experience", factor:"진로", needs:["topic"],
    text:"{topic} 활동에는 스스로 찾아서 참여했나요, 학교에서 마련한 프로그램이었나요?",
    purpose:"진로 탐색이 스스로 시작된 것인지 확인합니다.",
    tails:["참여하기 전에 알고 싶었던 것은 무엇인가요?","그 궁금증은 활동을 하고 나서 얼마나 풀렸나요?"] },
  { id:"jr-m1-03", area:["jinro"], intent:"motive", depth:1, kind:"experience", factor:"진로", needs:["book"],
    text:"진로활동에서 {book|을} 고른 이유는 무엇인가요?",
    purpose:"진로와 관련된 독서를 스스로 선택했는지 확인합니다.",
    tails:["그 책을 어떻게 알게 되었나요?","읽기 전에 그 분야에 대해 알고 있던 것은 무엇인가요?"] },
  // 선택·동기 · 깊이 2
  { id:"jr-m2-01", area:["jinro"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:[],
    text:"비슷한 분야의 다른 학과가 아니라 이 전공을 택한 이유는 무엇인가요?",
    purpose:"전공에 대한 이해와 선택의 근거를 확인합니다.",
    tails:["두 학과의 차이를 아는 대로 말해 주세요.","그 차이를 어떻게 알아보았나요?"] },
  { id:"jr-m2-02", area:["jinro"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic} 활동이 진로를 정하는 데 어떤 영향을 주었나요?",
    purpose:"기록된 활동과 진로 결정의 관계를 확인합니다.",
    tails:["그 활동 전에는 진로를 어떻게 생각했나요?","그 활동이 없었다면 다른 진로를 택했을까요?"] },
  { id:"jr-m2-03", area:["jinro"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:[],
    text:"학년에 따라 진로 희망이 달라졌다면, 바뀐 이유를 말해 주세요.",
    purpose:"진로 변경의 이유가 탐색의 결과인지 확인합니다.",
    tails:["바뀌기 전 진로를 위해 한 활동은 지금 어떻게 쓰이나요?","지금 진로가 또 바뀔 가능성은 없나요?"] },
  // 선택·동기 · 깊이 3
  { id:"jr-m3-01", area:["jinro"], intent:"motive", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"지금 진로를 택하지 않았다면 어떤 길을 택했을 것 같나요? 두 길의 공통점은 무엇인가요?",
    purpose:"진로 선택의 바탕에 있는 일관된 관심을 확인합니다.",
    tails:["그 길을 택하지 않은 이유는 무엇인가요?","공통점이 본인의 어떤 면을 보여 준다고 생각하나요?"] },
  { id:"jr-m3-02", area:["jinro"], intent:"motive", depth:3, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic} 경험 하나로 진로를 정한 것은 성급하다는 말을 듣는다면 어떻게 답하겠습니까?",
    purpose:"진로 결정의 근거가 여러 경험에 걸쳐 있는지 봅니다.",
    tails:["진로를 정하는 데 근거가 된 다른 경험은 무엇인가요?","진로에 대해 아직 확인하지 못한 것은 무엇인가요?"] },
  { id:"jr-m3-03", area:["jinro"], intent:"motive", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"이 분야의 전망이 나빠진다는 예측이 있다면 그래도 같은 선택을 하겠습니까?",
    purpose:"진로 선택의 동기가 얼마나 단단한지 확인합니다.",
    tails:["선택을 유지하는 이유는 무엇인가요?","전망이 바뀔 때를 대비해 무엇을 준비하겠습니까?"] },
  // 과정·역할 · 깊이 1
  { id:"jr-p1-01", area:["jinro"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:["topic"],
    text:"진로활동의 {topic} 활동에서 본인이 직접 조사하거나 만든 것은 무엇인가요?",
    purpose:"진로활동에서의 실제 수행 내용을 확인합니다.",
    tails:["조사한 내용 가운데 가장 공들인 부분은 무엇인가요?","결과물은 어떤 형태로 정리했나요?"] },
  { id:"jr-p1-02", area:["jinro"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"이 진로활동에서 무엇을 했는지 구체적으로 말해 주세요. 듣기만 한 활동이었나요?",
    purpose:"수동적 참여였는지 능동적 참여였는지 확인합니다.",
    tails:["활동 중에 직접 질문하거나 발표한 내용이 있나요?","활동 뒤에 따로 정리하거나 찾아본 것은 무엇인가요?"] },
  { id:"jr-p1-03", area:["jinro"], intent:"process", depth:1, kind:"concept", factor:"진로", needs:["book"],
    text:"{book}에서 진로와 관련해 가장 주의 깊게 읽은 부분은 어디인가요?",
    purpose:"진로 독서의 내용을 구체적으로 기억하는지 확인합니다.",
    tails:["그 부분의 내용을 간단히 설명해 주세요.","그 부분이 본인의 진로 생각과 어떻게 이어지나요?"] },
  // 과정·역할 · 깊이 2
  { id:"jr-p2-01", area:["jinro"], intent:"process", depth:2, kind:"experience", factor:"진로", needs:["topic"],
    text:"{topic} 활동을 하면서 진로 정보를 어디에서, 어떻게 찾았나요?",
    purpose:"진로 정보를 스스로 찾고 확인하는 방법을 봅니다.",
    tails:["그 정보가 정확한지 어떻게 확인했나요?","찾은 정보 가운데 예상과 달랐던 것은 무엇인가요?"] },
  { id:"jr-p2-02", area:["jinro"], intent:"process", depth:2, kind:"experience", factor:"진로", needs:[],
    text:"진로를 알아보려고 학교 안에서 스스로 찾아서 한 일은 무엇인가요?",
    purpose:"진로 탐색의 주도성과 실행력을 확인합니다.",
    tails:["그 일을 하게 된 계기는 무엇인가요?","그 과정에서 가장 어려웠던 점은 어떻게 풀었나요?"] },
  { id:"jr-p2-03", area:["jinro"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"진로 탐구로 {topic|을} 다룰 때 어떤 순서로 조사하고 정리했나요?",
    purpose:"진로 탐구의 과정이 체계적이었는지 확인합니다.",
    tails:["시간이 가장 많이 든 단계는 어디였나요?","정리하면서 뺀 내용은 무엇이고, 왜 뺐나요?"] },
  // 과정·역할 · 깊이 3
  { id:"jr-p3-01", area:["jinro"], intent:"process", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"진로를 탐색한 방법 가운데 가장 부족했다고 생각하는 것은 무엇인가요?",
    purpose:"진로 탐색 과정을 비판적으로 돌아보는지 확인합니다.",
    tails:["그 부족함 때문에 놓친 정보는 무엇일까요?","입학 뒤에는 어떻게 보완하겠습니까?"] },
  { id:"jr-p3-02", area:["jinro"], intent:"process", depth:3, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic} 활동에서 얻은 정보가 한쪽에 치우쳤을 가능성은 없나요? 어떻게 확인하겠습니까?",
    purpose:"정보의 편향을 의식하고 검증하려는 태도를 봅니다.",
    tails:["반대되는 정보를 찾아본 적이 있나요?","치우친 정보였다면 진로 판단이 어떻게 달라질까요?"] },
  // 개념·원리 · 깊이 1
  { id:"jr-c1-01", area:["jinro"], intent:"concept", depth:1, kind:"concept", factor:"진로", needs:[],
    text:"지원한 전공에서 무엇을 배우는지 아는 대로 말해 주세요.",
    purpose:"전공에 대한 기본 이해를 확인합니다.",
    tails:["그 가운데 가장 기대되는 과목은 무엇인가요?","가장 어려울 것 같은 과목은 무엇이고, 이유는 무엇인가요?"] },
  { id:"jr-c1-02", area:["jinro"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["concept"],
    text:"진로활동에서 {concept|을} 다뤘다고 되어 있습니다. 전공 분야에서 어떤 뜻으로 쓰는 말인가요?",
    purpose:"진로활동에서 다룬 개념을 이해하고 있는지 확인합니다.",
    tails:["이 개념을 어디에서 배웠나요?","전공 분야에서 이 개념이 왜 중요한가요?"] },
  // 개념·원리 · 깊이 2
  { id:"jr-c2-01", area:["jinro"], intent:"concept", depth:2, kind:"concept", factor:"진로", needs:["topic"],
    text:"{topic|과} 관련해 이 분야에서 요즘 중요하게 다뤄지는 쟁점을 하나 설명해 보세요.",
    purpose:"전공 분야의 흐름에 관심을 두고 있는지 확인합니다.",
    tails:["그 쟁점에서 입장이 갈리는 지점은 어디인가요?","본인은 어느 쪽에 더 동의하나요?"] },
  { id:"jr-c2-02", area:["jinro"], intent:"concept", depth:2, kind:"concept", factor:"진로", needs:["concept"],
    text:"{concept|이} 희망 진로의 실제 일에서 어떻게 쓰이는지 설명해 보세요.",
    purpose:"개념과 진로 분야의 연결을 이해하는지 확인합니다.",
    tails:["그 내용을 어떻게 알게 되었나요?","고등학교에서 배운 내용과는 어디에서 연결되나요?"] },
  { id:"jr-c2-03", area:["jinro"], intent:"concept", depth:2, kind:"concept", factor:"진로", needs:[],
    text:"희망하는 직업이 하는 일을 구체적으로 설명해 보세요. 흔히 하는 오해가 있다면 함께 말해 주세요.",
    purpose:"직업에 대한 이해가 구체적이고 정확한지 확인합니다.",
    tails:["그 일에 꼭 필요한 역량은 무엇이라고 보나요?","그 역량을 기르려고 고등학교에서 한 일은 무엇인가요?"] },
  // 개념·원리 · 깊이 3
  { id:"jr-c3-01", area:["jinro"], intent:"concept", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"희망 분야에 새로운 기술이 들어오면 하는 일이 어떻게 달라질지 예상해 보세요.",
    purpose:"분야의 변화를 근거 있게 내다보는지 확인합니다.",
    tails:["달라지지 않을 부분은 무엇이라고 보나요?","그 변화에 맞춰 무엇을 더 배워야 할까요?"] },
  { id:"jr-c3-02", area:["jinro"], intent:"concept", depth:3, kind:"opinion", factor:"진로", needs:["concept"],
    text:"{concept|이} 앞으로 이 분야에서 덜 중요해지거나 바뀔 가능성은 없을까요?",
    purpose:"지식을 고정된 것으로 보지 않고 변화 가능성을 생각하는지 봅니다.",
    tails:["그렇게 생각하는 근거는 무엇인가요?","바뀐다면 무엇이 그 자리를 채울까요?"] },
  { id:"jr-c3-03", area:["jinro"], intent:"concept", depth:3, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic} 활동에서 본 직업이나 학문의 모습에 한계나 문제점이 있다면 무엇인가요?",
    purpose:"희망 분야를 비판적으로도 볼 수 있는지 확인합니다.",
    tails:["그 문제를 해결하려는 시도를 알고 있나요?","본인이라면 어떻게 접근하겠습니까?"] },
  // 배움·변화 · 깊이 1
  { id:"jr-g1-01", area:["jinro"], intent:"growth", depth:1, kind:"experience", factor:"진로", needs:["topic"],
    text:"{topic} 활동을 통해 진로에 대해 새로 알게 된 것은 무엇인가요?",
    purpose:"진로활동에서 얻은 구체적인 배움을 확인합니다.",
    tails:["알기 전에는 어떻게 생각했나요?","새로 알게 된 뒤 무엇을 더 찾아보았나요?"] },
  { id:"jr-g1-02", area:["jinro"], intent:"growth", depth:1, kind:"experience", factor:"진로", needs:[],
    text:"이 진로활동에서 가장 인상 깊었던 내용 한 가지를 말해 주세요.",
    purpose:"활동 내용을 실제로 기억하고 의미를 두는지 확인합니다.",
    tails:["왜 그 내용이 인상 깊었나요?","그 내용이 진로 계획에 반영된 부분이 있나요?"] },
  // 배움·변화 · 깊이 2
  { id:"jr-g2-01", area:["jinro"], intent:"growth", depth:2, kind:"experience", factor:"진로", needs:[],
    text:"진로를 탐색하면서 스스로에 대해 새로 알게 된 점은 무엇인가요?",
    purpose:"진로 탐색이 자기 이해로 이어졌는지 확인합니다.",
    tails:["그것을 알게 된 경험을 말해 주세요.","그 점이 지원 전공과 잘 맞는다고 보는 이유는 무엇인가요?"] },
  { id:"jr-g2-02", area:["jinro"], intent:"growth", depth:2, kind:"experience", factor:"진로", needs:["topic"],
    text:"{topic} 활동을 한 뒤 학교 공부나 과목 선택에서 달라진 것이 있나요?",
    purpose:"진로활동이 실제 행동의 변화로 이어졌는지 확인합니다.",
    tails:["달라진 것을 구체적인 사례로 말해 주세요.","그 변화가 성적이나 활동에 어떤 결과를 가져왔나요?"] },
  { id:"jr-g2-03", area:["jinro"], intent:"growth", depth:2, kind:"experience", factor:"진로", needs:["book"],
    text:"{book}에서 희망 분야의 어려움이나 어두운 면을 본 적이 있나요? 그것을 보고 어떤 생각을 했나요?",
    purpose:"진로의 현실적인 면까지 살펴보았는지 확인합니다.",
    tails:["그런데도 이 분야를 택한 이유는 무엇인가요?","그 어려움을 직접 겪는다면 어떻게 하겠습니까?"] },
  // 배움·변화 · 깊이 3
  { id:"jr-g3-01", area:["jinro"], intent:"growth", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"진로 준비에서 아직 부족한 점은 무엇이고, 입학 뒤 1년 동안 어떻게 채우겠습니까?",
    purpose:"부족함을 알고 현실적인 계획을 세우는지 확인합니다.",
    tails:["가장 먼저 할 일 하나를 꼽는다면 무엇인가요?","계획대로 되지 않으면 어떻게 조정하겠습니까?"] },
  { id:"jr-g3-02", area:["jinro"], intent:"growth", depth:3, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic} 활동에서 배운 것이 희망 진로가 아닌 다른 분야에서도 쓸모가 있을까요? 예를 들어 보세요.",
    purpose:"배움을 진로 밖으로도 넓혀 생각하는지 봅니다.",
    tails:["그 분야에서는 어떤 점이 달라져야 하나요?","그렇게 넓게 쓰일 수 있는 까닭은 무엇이라고 보나요?"] },
  // 확장·가정 · 깊이 1
  { id:"jr-e1-01", area:["jinro"], intent:"extend", depth:1, kind:"experience", factor:"진로", needs:[],
    text:"진로활동에서 생긴 관심이 교과 수업이나 동아리로 이어진 사례가 있나요?",
    purpose:"진로 관심이 다른 영역의 활동으로 이어졌는지 확인합니다.",
    tails:["어떤 과목, 어떤 활동이었나요?","이어 가면서 관심이 더 구체적으로 바뀌었나요?"] },
  { id:"jr-e1-02", area:["jinro"], intent:"extend", depth:1, kind:"experience", factor:"진로", needs:["topic"],
    text:"{topic} 활동을 계기로 과목을 선택하거나 새로 시작한 활동이 있나요?",
    purpose:"진로활동이 이후의 선택에 영향을 주었는지 확인합니다.",
    tails:["그 선택은 기대만큼 도움이 되었나요?","도움이 되지 않은 부분은 무엇이었나요?"] },
  // 확장·가정 · 깊이 2
  { id:"jr-e2-01", area:["jinro"], intent:"extend", depth:2, kind:"experience", factor:"진로", needs:[],
    text:"진로활동에서 세운 계획 가운데 실제로 실천한 것과 못 한 것을 나누어 말해 주세요.",
    purpose:"계획을 실행으로 옮기는 힘을 확인합니다.",
    tails:["못 한 것은 이유가 무엇인가요?","대학에서는 그 계획을 어떻게 이어 가겠습니까?"] },
  { id:"jr-e2-02", area:["jinro"], intent:"extend", depth:2, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic} 활동에서 생긴 관심을 대학에서는 어떤 과목이나 활동으로 이어 가고 싶나요?",
    purpose:"고교의 진로 탐색과 대학 학업 계획의 연결을 봅니다.",
    tails:["그 과목에서 무엇을 배우는지 알아본 적이 있나요?","관심이 바뀐다면 어떻게 하겠습니까?"] },
  { id:"jr-e2-03", area:["jinro"], intent:"extend", depth:2, kind:"opinion", factor:"진로", needs:["concept"],
    text:"{concept|을} 대학에서 더 깊이 공부한다면 어떤 질문에서 시작하겠습니까?",
    purpose:"관심 개념을 학문적 질문으로 발전시키는지 확인합니다.",
    tails:["그 질문이 중요한 이유는 무엇인가요?","그 질문에 답하려면 어떤 공부가 먼저 필요한가요?"] },
  // 확장·가정 · 깊이 3
  { id:"jr-e3-01", area:["jinro"], intent:"extend", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"희망 분야에서 풀고 싶은 문제를 하나 꼽고, 어떻게 접근할지 말해 보세요.",
    purpose:"진로에 대한 문제의식과 사고의 깊이를 확인합니다.",
    tails:["그 문제가 아직 풀리지 않은 이유는 무엇이라고 보나요?","본인의 접근에서 예상되는 한계는 무엇인가요?"] },
  { id:"jr-e3-02", area:["jinro"], intent:"extend", depth:3, kind:"opinion", factor:"진로", needs:["topic"],
    text:"{topic|과} 관련해 본인과 생각이 다른 사람은 어떤 주장을 할까요? 그 주장을 평가해 보세요.",
    purpose:"반대 관점을 이해하고 평가하는 능력을 봅니다.",
    tails:["그 주장에서 인정할 부분은 무엇인가요?","그 부분을 받아들이면 본인의 생각은 어떻게 달라지나요?"] },
  { id:"jr-e3-03", area:["jinro"], intent:"extend", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"희망 진로와 본인의 성향이 맞지 않는다는 말을 듣는다면 어떻게 반박하겠습니까?",
    purpose:"자기 이해를 바탕으로 진로 적합성을 설명하는지 봅니다.",
    tails:["반박의 근거가 되는 기록이나 경험은 무엇인가요?","그 말이 맞는 부분이 있다면 어떻게 보완하겠습니까?"] },

  /* ════════ 행동특성 및 종합의견 (haengteuk) ════════ */
  // 선택·동기 · 깊이 2
  { id:"ht-m2-01", area:["haengteuk"], intent:"motive", depth:2, kind:"opinion", factor:"공동체", needs:[],
    text:"행동특성에 꾸준히 해 온 일이 적혀 있다면, 그 일을 계속한 이유는 무엇인가요?",
    purpose:"꾸준함의 바탕에 있는 동기와 가치관을 확인합니다.",
    tails:["그만두고 싶었던 때는 없었나요?","그 일이 본인에게 남긴 것은 무엇인가요?"] },
  // 과정·역할 · 깊이 1
  { id:"ht-p1-01", area:["haengteuk"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"선생님이 적어 주신 장점 가운데 가장 본인다운 것은 무엇이고, 그것을 보여 주는 사례는 무엇인가요?",
    purpose:"교사의 평가를 뒷받침하는 구체적인 사례가 있는지 확인합니다.",
    tails:["그 사례에서 본인이 실제로 한 행동을 더 구체적으로 말해 주세요.","같은 모습을 다른 상황에서도 보인 적이 있나요?"] },
  { id:"ht-p1-02", area:["haengteuk"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"행동특성에 적힌 표현 하나를 골라, 그 표현이 나오게 된 행동을 구체적으로 말해 주세요.",
    purpose:"기록된 평가가 실제 행동에서 나온 것인지 확인합니다.",
    tails:["그 행동을 얼마나 오래, 꾸준히 했나요?","꾸준히 하기 어려웠던 때는 어떻게 넘겼나요?"] },
  { id:"ht-p1-03", area:["haengteuk"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"행동특성에 적힌 평가 가운데 스스로는 잘 몰랐던 모습이 있나요?",
    purpose:"자기 이해의 정도와 교사 평가에 대한 생각을 확인합니다.",
    tails:["선생님이 왜 그렇게 보셨다고 생각하나요?","그 평가에 동의하나요? 이유도 말해 주세요."] },
  { id:"ht-p1-04", area:["haengteuk"], intent:"process", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"행동특성에 {role|을} 맡았다는 내용이 있습니다. 한 해 동안 구체적으로 무엇을 했나요?",
    purpose:"맡은 역할을 책임 있게 수행했는지 확인합니다.",
    tails:["가장 신경 쓴 일은 무엇인가요?","맡은 일 가운데 잘하지 못한 것은 무엇인가요?"] },
  { id:"ht-p1-05", area:["haengteuk"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:["topic"],
    text:"행동특성에 {topic|이} 언급되어 있습니다. 어떤 활동이었는지 말해 주세요.",
    purpose:"교사가 따로 기록한 활동의 실제 내용을 확인합니다.",
    tails:["선생님이 이 활동을 따로 적으신 이유가 무엇이라고 생각하나요?","이 활동에서 본인이 보여 준 모습은 무엇인가요?"] },
  // 과정·역할 · 깊이 2
  { id:"ht-p2-01", area:["haengteuk"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"학급에서 친구와 의견이 맞지 않았던 경험과, 그때 본인이 한 행동을 말해 주세요.",
    purpose:"갈등 상황에서의 태도와 해결 방식을 확인합니다.",
    tails:["상대 친구는 왜 그렇게 생각했을까요?","지금이라면 다르게 할 부분이 있나요?"] },
  { id:"ht-p2-02", area:["haengteuk"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"학급에서 누군가를 도운 경험이 기록되어 있다면, 어떤 상황이었는지 말해 주세요.",
    purpose:"배려와 나눔이 실제 행동으로 나타났는지 확인합니다.",
    tails:["돕기로 한 이유는 무엇인가요?","그 친구에게 실제로 도움이 되었는지 어떻게 알았나요?"] },
  { id:"ht-p2-03", area:["haengteuk"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"여럿이 하는 일에서 본인은 주로 어떤 역할을 맡는 편인가요? 기록에 있는 사례로 말해 주세요.",
    purpose:"협업에서의 역할과 자기 이해를 확인합니다.",
    tails:["그 역할이 잘 맞지 않았던 경우도 있나요?","다른 역할을 맡아야 했다면 어떻게 했을까요?"] },
  { id:"ht-p2-04", area:["haengteuk"], intent:"process", depth:2, kind:"fact", factor:"신뢰", needs:[],
    text:"기록에 '다소', '~한 편이나', '노력이 필요함' 같은 표현이 있다면, 어떤 상황을 두고 쓴 말이라고 생각하나요?",
    purpose:"약점으로 읽힐 수 있는 표현을 본인이 어떻게 이해하는지 확인합니다.",
    tails:["그 평가에 동의하나요?","그 뒤에 달라진 점이 있다면 사례로 말해 주세요."] },
  // 개념·원리 · 깊이 2
  { id:"ht-c2-01", area:["haengteuk"], intent:"concept", depth:2, kind:"opinion", factor:"공동체", needs:[],
    text:"기록에 '배려'나 '책임감' 같은 말이 있다면, 본인은 그 말을 어떤 행동으로 정의하나요?",
    purpose:"인성 덕목을 자기 기준으로 구체화하고 있는지 확인합니다.",
    tails:["그 정의에 맞지 않게 행동한 적도 있나요?","그때 무엇을 배웠나요?"] },
  // 배움·변화 · 깊이 1
  { id:"ht-g1-01", area:["haengteuk"], intent:"growth", depth:1, kind:"experience", factor:"공동체", needs:[],
    text:"고등학교 3년 동안 본인이 가장 많이 달라진 점은 무엇인가요?",
    purpose:"성장 과정을 스스로 설명할 수 있는지 확인합니다.",
    tails:["달라지게 된 계기는 무엇이었나요?","주변에서 그 변화를 알아본 사람이 있나요?"] },
  // 배움·변화 · 깊이 2
  { id:"ht-g2-01", area:["haengteuk"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"학년이 올라가면서 선생님의 평가가 달라진 부분이 있다면, 왜 달라졌다고 생각하나요?",
    purpose:"학년별 기록의 변화와 그 이유를 확인합니다.",
    tails:["달라지려고 일부러 한 일이 있나요?","달라지지 않은 부분은 무엇인가요?"] },
  { id:"ht-g2-02", area:["haengteuk"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"학교생활에서 가장 힘들었던 시기는 언제였고, 어떻게 지나왔나요?",
    purpose:"어려움을 견디고 넘어서는 과정을 확인합니다.",
    tails:["그때 가장 도움이 된 것은 무엇인가요?","같은 어려움을 겪는 친구에게 무엇을 말해 주겠습니까?"] },
  { id:"ht-g2-03", area:["haengteuk"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"학교생활에서 스스로 가장 자랑스러웠던 순간은 언제인가요?",
    purpose:"본인이 가치 있게 여기는 것이 무엇인지 확인합니다.",
    tails:["그 순간을 위해 무엇을 했나요?","그 경험이 지금의 본인에게 어떤 영향을 주었나요?"] },
  { id:"ht-g2-04", area:["haengteuk"], intent:"growth", depth:2, kind:"fact", factor:"신뢰", needs:[],
    text:"선생님이 보완할 점으로 적으신 내용이 있다면, 그 뒤에 어떻게 노력했나요?",
    purpose:"지적받은 점을 받아들이고 고치려 했는지 확인합니다.",
    tails:["노력의 결과를 보여 주는 사례가 있나요?","아직 남아 있는 부분은 무엇인가요?"] },
  // 배움·변화 · 깊이 3
  { id:"ht-g3-01", area:["haengteuk"], intent:"growth", depth:3, kind:"experience", factor:"공동체", needs:[],
    text:"기록에 적힌 장점이 오히려 단점으로 작용한 경험이 있나요?",
    purpose:"자신의 특성을 여러 면에서 볼 수 있는지 확인합니다.",
    tails:["그때 어떻게 대처했나요?","장점을 살리면서 그 문제를 줄이는 방법은 무엇일까요?"] },
  // 확장·가정 · 깊이 2
  { id:"ht-e2-01", area:["haengteuk"], intent:"extend", depth:2, kind:"opinion", factor:"공동체", needs:[],
    text:"기록에 적힌 본인의 강점을 대학 생활에서 어떻게 쓰겠습니까?",
    purpose:"강점을 새로운 환경에 연결해 생각하는지 확인합니다.",
    tails:["그 강점이 필요한 상황을 하나 예로 들어 보세요.","강점만으로 부족한 상황에서는 어떻게 하겠습니까?"] },
  // 확장·가정 · 깊이 3
  { id:"ht-e3-01", area:["haengteuk"], intent:"extend", depth:3, kind:"opinion", factor:"공동체", needs:[],
    text:"대학에서 성향이 전혀 다른 사람과 한 조가 된다면, 기록에 적힌 본인의 모습 가운데 무엇이 도움이 되고 무엇이 걸림돌이 될까요?",
    purpose:"낯선 상황에 자신의 특성을 비추어 판단하는 능력을 봅니다.",
    tails:["걸림돌이 되는 부분은 어떻게 조절하겠습니까?","조절이 잘 안 되었던 경험이 있나요?"] },
  { id:"ht-e3-02", area:["haengteuk"], intent:"extend", depth:3, kind:"opinion", factor:"신뢰", needs:[],
    text:"행동특성의 평가가 실제보다 좋게 적힌 것이 아니냐는 질문을 받는다면 어떻게 답하겠습니까?",
    purpose:"기록의 신뢰성을 구체적인 사실로 뒷받침하는지 확인합니다.",
    tails:["평가를 뒷받침하는 사실을 하나 더 말해 주세요.","평가와 실제가 다른 부분이 있다면 무엇인가요?"] },

  /* ════════ 교과 이수·성적 (gwamok) ════════ */
  // 선택·동기 · 깊이 1
  { id:"gm-m1-01", area:["gwamok"], intent:"motive", depth:1, kind:"opinion", factor:"진로", needs:["subject"],
    text:"{subject} 과목을 선택한 이유는 무엇인가요?",
    purpose:"과목 선택에 본인의 목적과 기준이 있었는지 확인합니다.",
    tails:["선택할 때 함께 고민한 다른 과목은 무엇이었나요?","들어 보니 기대와 달랐던 점은 무엇인가요?"] },
  { id:"gm-m1-02", area:["gwamok"], intent:"motive", depth:1, kind:"opinion", factor:"진로", needs:[],
    text:"선택 과목을 고를 때 가장 중요하게 본 기준은 무엇이었나요?",
    purpose:"과목 선택의 원칙이 진로와 이어져 있는지 확인합니다.",
    tails:["그 기준 때문에 포기한 과목이 있나요?","지금 다시 고른다면 같은 기준을 쓰겠습니까?"] },
  // 선택·동기 · 깊이 2
  { id:"gm-m2-01", area:["gwamok"], intent:"motive", depth:2, kind:"fact", factor:"진로", needs:[],
    text:"전공과 관련이 깊은 과목 가운데 이수하지 않은 과목이 있다면, 이유를 말해 주세요.",
    purpose:"미이수의 사정과 그것을 보완하려는 노력을 확인합니다.",
    tails:["학교에 개설되지 않았다면 다른 방법으로 보완했나요?","그 과목 내용 가운데 지금 아는 것을 말해 보세요."] },
  { id:"gm-m2-02", area:["gwamok"], intent:"motive", depth:2, kind:"fact", factor:"진로", needs:["subject"], cond:"nottaken",
    text:"{subject} 과목을 이수하지 않았습니다. 이유를 말해 주고, 그 내용을 어떻게 보완했는지도 알려 주세요.",
    purpose:"전공 관련 과목 미이수의 사유와 보완 노력을 확인합니다.",
    tails:["보완하면서 공부한 내용 가운데 하나를 설명해 보세요.","대학에서 이 과목 내용이 필요해지면 어떻게 따라가겠습니까?"] },
  { id:"gm-m2-03", area:["gwamok"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:[],
    text:"과목을 고를 때 전공과의 관련성과 성적 받기 쉬운 정도가 부딪힌 적이 있나요? 어떻게 결정했나요?",
    purpose:"과목 선택에서 무엇을 우선했는지 확인합니다.",
    tails:["그 결정의 결과는 어땠나요?","후배가 같은 고민을 한다면 무엇을 권하겠습니까?"] },
  { id:"gm-m2-04", area:["gwamok"], intent:"motive", depth:2, kind:"fact", factor:"학업", needs:["subject"],
    text:"{subject} 과목을 듣기 전에 먼저 배워야 하는 과목은 무엇이었고, 그 순서를 고려해 선택했나요?",
    purpose:"과목의 위계를 이해하고 계획적으로 이수했는지 확인합니다.",
    tails:["앞 과목에서 배운 내용 가운데 무엇이 가장 쓰였나요?","순서를 지키지 못한 부분이 있다면 어떻게 메웠나요?"] },
  // 과정·역할 · 깊이 1
  { id:"gm-p1-01", area:["gwamok"], intent:"process", depth:1, kind:"opinion", factor:"진로", needs:[],
    text:"전공과 가장 관련이 깊다고 생각하는 이수 과목을 하나 꼽고, 그 과목에서 무엇을 배웠는지 말해 주세요.",
    purpose:"이수 과목과 전공의 관계를 스스로 설명하는지 확인합니다.",
    tails:["그 과목에서 가장 깊이 공부한 내용은 무엇인가요?","전공 공부에 더 필요한데 듣지 못한 과목은 무엇인가요?"] },
  { id:"gm-p1-02", area:["gwamok"], intent:"process", depth:1, kind:"fact", factor:"신뢰", needs:["subject"],
    text:"{subject} 과목은 몇 학년 때 들었고, 수업은 주로 어떤 방식으로 진행되었나요?",
    purpose:"이수 사실과 수업 참여의 실제 모습을 확인합니다.",
    tails:["그 수업에서 본인이 가장 적극적으로 한 것은 무엇인가요?","수업 방식이 본인에게 맞지 않았던 점은 없었나요?"] },
  // 과정·역할 · 깊이 2
  { id:"gm-p2-01", area:["gwamok"], intent:"process", depth:2, kind:"fact", factor:"학업", needs:[], cond:"up",
    text:"성적이 오른 학기가 있습니다. 무엇을 바꿨기에 올랐다고 생각하나요?",
    purpose:"성적 상승의 원인을 스스로 분석하고 있는지 확인합니다.",
    tails:["바꾼 공부 방법을 구체적으로 말해 주세요.","그 방법이 통하지 않은 과목은 없었나요?"] },
  { id:"gm-p2-02", area:["gwamok"], intent:"process", depth:2, kind:"fact", factor:"학업", needs:[], cond:"down",
    text:"성적이 떨어진 학기가 있습니다. 원인을 무엇이라고 보고, 그 뒤에 어떻게 했나요?",
    purpose:"성적 하락의 원인을 정직하게 보고 대처했는지 확인합니다.",
    tails:["원인을 그렇게 판단한 근거는 무엇인가요?","그 뒤의 변화는 기록 어디에서 확인할 수 있나요?"] },
  { id:"gm-p2-03", area:["gwamok"], intent:"process", depth:2, kind:"fact", factor:"학업", needs:["subject"], cond:"low",
    text:"{subject} 과목 성적이 다른 과목보다 낮습니다. 이유가 무엇이라고 생각하나요?",
    purpose:"취약 과목의 원인을 알고 보완하려 했는지 확인합니다.",
    tails:["성적을 올리려고 시도한 방법은 무엇인가요?","대학에서 이 과목과 관련된 공부를 어떻게 따라가겠습니까?"] },
  { id:"gm-p2-04", area:["gwamok"], intent:"process", depth:2, kind:"fact", factor:"학업", needs:["subject"], cond:"up",
    text:"{subject} 과목 성적이 올랐습니다. 공부 방법에서 무엇이 달라졌나요?",
    purpose:"성적 변화 뒤에 있는 학습 방법의 변화를 확인합니다.",
    tails:["달라진 방법을 찾게 된 계기는 무엇인가요?","그 방법을 계속 쓰기 어려웠던 때는 없었나요?"] },
  { id:"gm-p2-05", area:["gwamok"], intent:"process", depth:2, kind:"fact", factor:"학업", needs:[],
    text:"가장 어려웠던 과목은 무엇이었고, 어떻게 공부했나요?",
    purpose:"어려운 과목을 대하는 태도와 학습 전략을 확인합니다.",
    tails:["어렵다고 느낀 이유를 구체적으로 말해 주세요.","그 과목에서 끝내 해결하지 못한 부분은 무엇인가요?"] },
  { id:"gm-p2-06", area:["gwamok"], intent:"process", depth:2, kind:"fact", factor:"학업", needs:["subject"],
    text:"{subject} 과목을 공부할 때 본인만의 방법이 있었나요? 구체적으로 말해 주세요.",
    purpose:"자기주도적인 학습 방법을 갖추었는지 확인합니다.",
    tails:["그 방법을 찾기까지 어떤 시행착오가 있었나요?","다른 과목에도 그 방법이 통했나요?"] },
  // 개념·원리 · 깊이 2
  { id:"gm-c2-01", area:["gwamok"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:["subject"],
    text:"{subject} 과목에서 배운 내용 가운데 전공 공부의 바탕이 될 것을 하나 꼽고 설명해 보세요.",
    purpose:"이수 과목의 핵심 내용을 이해하고 전공과 잇는지 확인합니다.",
    tails:["그 내용이 전공에서 어떻게 쓰이는지 아는 대로 말해 주세요.","그 내용에서 아직 자신 없는 부분은 무엇인가요?"] },
  // 배움·변화 · 깊이 1
  { id:"gm-g1-01", area:["gwamok"], intent:"growth", depth:1, kind:"opinion", factor:"학업", needs:[],
    text:"가장 자신 있는 과목은 무엇이고, 그 이유는 무엇인가요?",
    purpose:"강점 과목과 그 근거를 스스로 설명하는지 확인합니다.",
    tails:["그 과목에서 가장 깊이 공부한 내용은 무엇인가요?","자신 있는 과목과 전공은 어떻게 이어지나요?"] },
  // 배움·변화 · 깊이 2
  { id:"gm-g2-01", area:["gwamok"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:["subject"],
    text:"{subject} 과목에서 한 탐구나 프로젝트 가운데 하나를 소개해 주세요. 무엇을 알아냈나요?",
    purpose:"선택 과목에서의 탐구 경험과 배움을 확인합니다.",
    tails:["그 탐구에서 가장 어려웠던 점은 무엇인가요?","그 탐구가 이후 공부에 어떤 영향을 주었나요?"] },
  { id:"gm-g2-02", area:["gwamok"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"진로선택 과목이나 융합선택 과목에서 한 활동 가운데 일반 과목과 가장 달랐던 경험은 무엇인가요?",
    purpose:"선택 과목에서 얻은 고유한 배움을 확인합니다.",
    tails:["그 경험에서 새로 익힌 것은 무엇인가요?","그 과목을 듣지 않았다면 무엇을 몰랐을까요?"] },
  { id:"gm-g2-03", area:["gwamok"], intent:"growth", depth:2, kind:"fact", factor:"학업", needs:[],
    text:"학년이 올라가며 성적 흐름이 어떻게 변했는지 스스로 설명해 주세요.",
    purpose:"성적 추이를 객관적으로 파악하고 있는지 확인합니다.",
    tails:["흐름이 바뀐 시점에 무슨 일이 있었나요?","지금의 공부 방식에서 유지할 것과 바꿀 것은 무엇인가요?"] },
  // 확장·가정 · 깊이 2
  { id:"gm-e2-01", area:["gwamok"], intent:"extend", depth:2, kind:"fact", factor:"학업", needs:[],
    text:"학교에 개설되지 않아 듣지 못한 과목이 있다면, 대신 어떤 방법으로 공부했나요?",
    purpose:"주어진 여건에서 배움의 기회를 스스로 찾았는지 확인합니다.",
    tails:["그렇게 공부한 내용 가운데 하나를 설명해 보세요.","혼자 공부하면서 부족했던 점은 무엇인가요?"] },
  // 확장·가정 · 깊이 3
  { id:"gm-e3-01", area:["gwamok"], intent:"extend", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"과목 선택을 처음부터 다시 한다면 무엇을 바꾸겠습니까?",
    purpose:"이수 과정을 돌아보고 평가하는 능력을 확인합니다.",
    tails:["바꾸려는 이유는 무엇인가요?","바꾸지 않을 과목 하나와 그 이유를 말해 주세요."] },
  { id:"gm-e3-02", area:["gwamok"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["subject"], cond:"low",
    text:"성적만 보면 {subject} 과목의 이해가 충분하지 않다고 볼 수도 있습니다. 어떻게 답하겠습니까?",
    purpose:"낮은 성적에 대한 지적에 사실과 근거로 답하는지 확인합니다.",
    tails:["이해하고 있다는 것을 보여 줄 내용을 하나 설명해 보세요.","부족한 부분은 입학 전까지 어떻게 채우겠습니까?"] },

  /* ════════ 출결 (chulgyeol) ════════ */
  // 과정·역할 · 깊이 1
  { id:"cg-p1-01", area:["chulgyeol"], intent:"process", depth:1, kind:"fact", factor:"신뢰", needs:[],
    text:"출결에 미인정 기록이 있습니다. 어떤 사정이었는지 말해 주세요.",
    purpose:"출결 기록의 사유를 사실대로 설명하는지 확인합니다.",
    tails:["그때 학교에는 어떻게 알렸나요?","같은 일이 다시 생기지 않게 무엇을 바꿨나요?"] },
  { id:"cg-p1-02", area:["chulgyeol"], intent:"process", depth:1, kind:"fact", factor:"신뢰", needs:[], cond:"late",
    text:"미인정 지각이 있습니다. 주로 어떤 이유였나요?",
    purpose:"지각의 원인을 숨기지 않고 말하는지 확인합니다.",
    tails:["지각이 되풀이되었다면 원인을 스스로 무엇이라고 보나요?","그 뒤 학기의 출결은 어떻게 달라졌나요?"] },
  { id:"cg-p1-03", area:["chulgyeol"], intent:"process", depth:1, kind:"fact", factor:"신뢰", needs:[], cond:"absent",
    text:"미인정 결석이 있습니다. 그날 무슨 일이 있었고, 그 뒤 어떻게 했나요?",
    purpose:"결석의 사유와 이후의 책임 있는 행동을 확인합니다.",
    tails:["빠진 수업은 어떻게 보충했나요?","그 일을 겪고 달라진 점은 무엇인가요?"] },
  { id:"cg-p1-04", area:["chulgyeol"], intent:"process", depth:1, kind:"fact", factor:"신뢰", needs:[], cond:"leave",
    text:"미인정 조퇴나 결과 기록이 있습니다. 사유를 설명해 주세요.",
    purpose:"조퇴·결과의 사유와 수업에 대한 태도를 확인합니다.",
    tails:["놓친 수업 내용은 어떻게 채웠나요?","그 일로 주변에 불편을 주었다면 어떻게 했나요?"] },
  // 과정·역할 · 깊이 2
  { id:"cg-p2-01", area:["chulgyeol"], intent:"process", depth:2, kind:"fact", factor:"신뢰", needs:[], cond:"many",
    text:"결석이나 조퇴가 많았던 학기가 있습니다. 그 기간의 학습 공백은 어떻게 메웠나요?",
    purpose:"공백을 스스로 메우려 한 노력과 방법을 확인합니다.",
    tails:["공백을 메우는 데 가장 도움이 된 것은 무엇인가요?","그 학기 성적이나 활동에 영향이 있었다면 어떻게 회복했나요?"] },
  // 배움·변화 · 깊이 2
  { id:"cg-g2-01", area:["chulgyeol"], intent:"growth", depth:2, kind:"fact", factor:"신뢰", needs:[],
    text:"출결 기록이 학년에 따라 다릅니다. 무엇이 달라졌나요?",
    purpose:"출결의 변화와 그 배경을 확인합니다.",
    tails:["달라지게 된 계기는 무엇인가요?","그 변화를 지금도 유지하고 있나요?"] },
  { id:"cg-g2-02", area:["chulgyeol"], intent:"growth", depth:2, kind:"fact", factor:"신뢰", needs:[],
    text:"미인정 기록이 생긴 뒤 생활 습관에서 실제로 바꾼 것은 무엇인가요?",
    purpose:"잘못을 돌아보고 행동을 고쳤는지 확인합니다.",
    tails:["바꾼 습관을 지금도 지키고 있나요?","지키기 어려웠던 때는 어떻게 했나요?"] },
  // 확장·가정 · 깊이 3
  { id:"cg-e3-01", area:["chulgyeol"], intent:"extend", depth:3, kind:"fact", factor:"신뢰", needs:[],
    text:"대학에서는 출석을 스스로 관리해야 합니다. 출결 기록에 비추어 어떻게 관리하겠습니까?",
    purpose:"같은 문제가 대학에서 되풀이되지 않을지 확인합니다.",
    tails:["스스로 정한 규칙이 있나요?","그 규칙이 무너졌을 때는 어떻게 다시 세우겠습니까?"] },
  { id:"cg-e3-02", area:["chulgyeol"], intent:"extend", depth:3, kind:"fact", factor:"신뢰", needs:[],
    text:"출결 기록만 보고 성실하지 않다고 판단하는 사람이 있다면 어떻게 답하겠습니까?",
    purpose:"약점에 대한 지적에 변명 없이 사실로 답하는지 확인합니다.",
    tails:["성실함을 보여 주는 다른 기록은 무엇인가요?","그 판단에서 인정할 부분은 무엇인가요?"] },

  /* ════════ 전 영역 공통 — 지시어형 (any) ════════ */
  // 선택·동기 · 깊이 1
  { id:"an-m1-01", area:["any"], intent:"motive", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"이 활동은 누가 먼저 하자고 했나요? 본인이 정한 부분은 어디까지인가요?",
    purpose:"활동의 출발과 본인의 선택 범위를 확인합니다.",
    tails:["본인이 정한 부분에서 가장 고민한 것은 무엇인가요?","다른 사람이 정한 부분에 의견을 낸 적이 있나요?"] },
  // 선택·동기 · 깊이 2
  { id:"an-m2-01", area:["any"], intent:"motive", depth:2, kind:"opinion", factor:"진로", needs:[],
    text:"꼭 하지 않아도 되는 활동이었다면, 그런데도 이 활동을 한 이유는 무엇인가요?",
    purpose:"활동에 참여한 내적 동기를 확인합니다.",
    tails:["그 이유는 활동이 끝날 때까지 그대로였나요?","이 활동 대신 하려고 했던 다른 일이 있었나요?"] },
  { id:"an-m2-02", area:["any"], intent:"motive", depth:2, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동을 시작할 때 세운 목표는 무엇이었나요? 목표를 그렇게 잡은 이유도 말해 주세요.",
    purpose:"목표를 스스로 세우고 그 이유를 설명할 수 있는지 봅니다.",
    tails:["목표를 얼마나 이루었다고 평가하나요?","이루지 못한 부분은 무엇 때문이었나요?"] },
  // 선택·동기 · 깊이 3
  { id:"an-m3-01", area:["any"], intent:"motive", depth:3, kind:"opinion", factor:"진로", needs:[],
    text:"같은 시간을 다른 활동에 썼다면 더 나았을 것이라고 생각해 본 적은 없나요?",
    purpose:"선택의 기회비용을 따져 보고 평가하는지 확인합니다.",
    tails:["그런데도 이 활동이 의미 있었다고 보는 이유는 무엇인가요?","다시 고른다면 시간을 어떻게 나누겠습니까?"] },
  // 과정·역할 · 깊이 1
  { id:"an-p1-01", area:["any"], intent:"process", depth:1, kind:"experience", factor:"소통", needs:[],
    text:"기록에 적힌 이 활동을 처음 듣는 사람에게 30초 안에 소개해 보세요.",
    purpose:"활동의 핵심을 간추려 전달할 수 있는지 확인합니다.",
    tails:["방금 소개에서 뺀 내용 가운데 가장 아쉬운 것은 무엇인가요?","이 활동에서 본인의 몫은 어느 부분이었나요?"] },
  { id:"an-p1-02", area:["any"], intent:"process", depth:1, kind:"experience", factor:"신뢰", needs:[],
    text:"이 기록에서 본인이 한 일과 다른 사람이 한 일을 나누어 말해 주세요.",
    purpose:"공동 활동에서 본인의 기여를 사실대로 구분하는지 확인합니다.",
    tails:["본인이 한 일 가운데 가장 어려웠던 것은 무엇인가요?","다른 사람이 한 일 가운데 본인이 설명할 수 있는 부분은 어디까지인가요?"] },
  // 과정·역할 · 깊이 2
  { id:"an-p2-01", area:["any"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"이 활동에서 가장 어려웠던 점은 무엇이었고, 어떻게 해결했나요?",
    purpose:"어려움을 만났을 때의 대처 방식을 확인합니다.",
    tails:["처음 시도한 방법이 통하지 않았다면 그다음에는 무엇을 했나요?","해결하지 못하고 남은 부분은 무엇인가요?"] },
  { id:"an-p2-02", area:["any"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"이 활동에서 스스로 판단해서 결정한 일 하나를 말해 주세요. 왜 그렇게 결정했나요?",
    purpose:"과정 속에서 본인의 판단이 들어간 지점을 확인합니다.",
    tails:["다른 선택지는 무엇이 있었나요?","그 결정의 결과는 어땠나요?"] },
  // 과정·역할 · 깊이 3
  { id:"an-p3-01", area:["any"], intent:"process", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동을 다시 한다면 과정에서 가장 먼저 바꿀 것은 무엇인가요?",
    purpose:"과정을 돌아보고 개선점을 찾는 능력을 확인합니다.",
    tails:["그것을 바꾸면 무엇이 좋아지나요?","바꾸면서 새로 생길 어려움은 무엇인가요?"] },
  // 개념·원리 · 깊이 1
  { id:"an-c1-01", area:["any"], intent:"concept", depth:1, kind:"concept", factor:"신뢰", needs:[],
    text:"이 기록에 나오는 낱말 가운데 뜻을 설명하기 가장 어려운 것은 무엇인가요? 설명해 보세요.",
    purpose:"기록에 쓰인 용어를 빠짐없이 이해하고 있는지 확인합니다.",
    tails:["그 낱말은 활동의 어느 장면에서 쓰였나요?","더 정확히 설명하려면 무엇을 찾아봐야 하나요?"] },
  // 개념·원리 · 깊이 2
  { id:"an-c2-01", area:["any"], intent:"concept", depth:2, kind:"concept", factor:"학업", needs:[],
    text:"이 활동과 관련된 교과 내용은 무엇이고, 둘이 어떻게 이어지는지 설명해 보세요.",
    purpose:"활동을 교과 학습과 연결해 이해하는지 확인합니다.",
    tails:["그 교과 내용을 한 문장으로 정리해 보세요.","교과 내용만으로는 설명되지 않는 부분은 무엇인가요?"] },
  // 개념·원리 · 깊이 3
  { id:"an-c3-01", area:["any"], intent:"concept", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동에서 내린 결론이 틀릴 수 있다면 어떤 경우일까요?",
    purpose:"자신의 결론을 의심하고 점검하는 태도를 봅니다.",
    tails:["그 경우를 확인하는 방법은 무엇인가요?","틀린 것으로 드러나면 무엇부터 다시 보겠습니까?"] },
  // 배움·변화 · 깊이 1
  { id:"an-g1-01", area:["any"], intent:"growth", depth:1, kind:"experience", factor:"학업", needs:[],
    text:"이 활동으로 얻은 것을 한 문장으로 말해 주세요.",
    purpose:"활동의 배움을 분명하게 정리하고 있는지 확인합니다.",
    tails:["그것을 얻었다고 느낀 순간은 언제였나요?","얻지 못해서 아쉬운 것은 무엇인가요?"] },
  // 배움·변화 · 깊이 2
  { id:"an-g2-01", area:["any"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"이 활동이 없었다면 지금의 본인에게서 무엇이 빠져 있을까요?",
    purpose:"활동이 본인의 성장에 준 영향을 확인합니다.",
    tails:["그 영향이 드러난 다른 기록이나 경험이 있나요?","그 영향은 지금도 이어지고 있나요?"] },
  // 배움·변화 · 깊이 3
  { id:"an-g3-01", area:["any"], intent:"growth", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동에서 배운 것 가운데 대학에서도 통할 것과 통하지 않을 것을 나누어 말해 보세요.",
    purpose:"배움의 적용 범위를 스스로 가늠하는지 봅니다.",
    tails:["통하지 않을 것이라고 본 이유는 무엇인가요?","그 부분은 대학에서 어떻게 새로 익히겠습니까?"] },
  // 확장·가정 · 깊이 1
  { id:"an-e1-01", area:["any"], intent:"extend", depth:1, kind:"experience", factor:"진로", needs:[],
    text:"이 활동과 이어지는 다른 기록이 학생부에 있나요? 어떻게 이어지는지 말해 주세요.",
    purpose:"기록 사이의 흐름과 관심의 일관성을 확인합니다.",
    tails:["두 기록 사이에 생각이 달라진 점은 무엇인가요?","이어지는 기록이 없다면 이유는 무엇인가요?"] },
  // 확장·가정 · 깊이 2
  { id:"an-e2-01", area:["any"], intent:"extend", depth:2, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동을 한 단계 발전시킨다면 다음에는 무엇을 하겠습니까?",
    purpose:"활동을 스스로 확장하는 사고를 확인합니다.",
    tails:["그것을 하려면 무엇이 더 필요한가요?","왜 그 방향이 가장 좋은 다음 단계라고 보나요?"] },
  // 확장·가정 · 깊이 3
  { id:"an-e3-01", area:["any"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:[],
    text:"이 활동의 조건 가운데 하나가 달랐다면 결과가 어떻게 바뀌었을지 예를 들어 말해 보세요.",
    purpose:"가정된 상황에서 근거를 들어 추론하는지 봅니다.",
    tails:["그렇게 추론한 근거는 무엇인가요?","그 추론이 틀릴 수 있는 이유를 하나 들어 보세요."] },
  { id:"an-e3-02", area:["any"], intent:"extend", depth:3, kind:"opinion", factor:"소통", needs:[],
    text:"이 활동의 의미가 크지 않다고 보는 사람에게 어떻게 설명하겠습니까?",
    purpose:"압박 상황에서 근거를 들어 차분히 설명하는지 확인합니다.",
    tails:["그 생각에서 맞는 부분은 무엇인가요?","그래도 이 활동을 기록에 남길 만한 이유는 무엇인가요?"] },

  /* ════════ 대학 가이드북에서 확인한 질문 방식 (대학 이름 없이 일반형으로 다시 씀) ════════ */
  { id:"st-c1-91", area:["seteuk"], intent:"concept", depth:1, kind:"concept", factor:"학업", needs:["concept"],
    text:"{concept|을} 교과서 문장이 아니라 본인의 말로 간단히 설명해 보세요.",
    purpose:"외운 정의가 아니라 개념을 실제로 이해했는지 확인합니다. 탐구 결과보다 먼저 확인하는 경우가 많습니다.",
    tails:["그 설명에서 가장 중요한 낱말 하나를 고른다면 무엇인가요?","이 개념이 탐구에서 어떤 역할을 했나요?"] },
  { id:"st-p2-91", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic|을} 탐구할 때 쓴 자료나 기준을 왜 그것으로 정했나요?",
    purpose:"자료·지표·가설을 스스로 따져 고른 것인지, 탐구 설계의 이유를 설명할 수 있는지 확인합니다.",
    tails:["다른 자료를 썼다면 결과가 어떻게 달라졌을까요?","그 기준을 정할 때 참고한 것은 무엇이었나요?"] },
  { id:"st-p2-92", area:["seteuk"], intent:"process", depth:2, kind:"experience", factor:"학업", needs:[],
    text:"이 탐구에서 조사 대상이나 실험 방법은 어떤 기준으로 정했나요?",
    purpose:"설문·실험이 기록되어 있으면 결과보다 방법을 정한 이유를 깊이 묻습니다.",
    tails:["대상의 수가 충분했다고 생각하나요?","방법을 다시 정한다면 무엇을 바꾸겠습니까?"] },
  { id:"st-g2-91", area:["seteuk"], intent:"growth", depth:2, kind:"experience", factor:"학업", needs:["topic"],
    text:"{topic}에서 아쉬웠던 점을 보완하려고 이어서 한 공부나 활동이 있나요?",
    purpose:"한계를 알아차린 뒤 스스로 후속 노력을 했는지, 탐구가 한 번으로 끝났는지 확인합니다.",
    tails:["그 후속 활동에서 새로 알게 된 것은 무엇인가요?","아직 풀리지 않은 궁금증이 있다면 무엇인가요?"] },
  { id:"st-e3-91", area:["seteuk"], intent:"extend", depth:3, kind:"opinion", factor:"학업", needs:["topic"],
    text:"{topic|이} 다룬 문제의 부정적인 영향을 줄이려면 어떤 노력이 필요하다고 생각하나요?",
    purpose:"사회 문제를 다룬 탐구가 문제 제기에서 멈추지 않고 해결 방안까지 고민했는지 확인합니다.",
    tails:["그 방법의 한계는 무엇인가요?","고등학생인 본인이 지금 할 수 있는 일은 무엇일까요?"] },
  { id:"st-p2-93", area:["seteuk"], intent:"process", depth:2, kind:"opinion", factor:"소통", needs:[],
    text:"이 수업의 토론에서 본인은 어떤 주장을 했고, 근거는 무엇이었나요?",
    purpose:"토론 기록이 있으면 당시의 주장과 근거를 지금도 조리 있게 다시 말할 수 있는지 확인합니다.",
    tails:["상대편의 가장 강한 반론은 무엇이었나요?","지금 다시 토론한다면 입장이 달라지나요?"] },
  { id:"st-p1-91", area:["seteuk"], intent:"process", depth:1, kind:"experience", factor:"공동체", needs:[],
    text:"이 수업의 모둠 활동에서 맡은 역할과 그때 겪은 어려움을 말해 주세요.",
    purpose:"세특에 협력 장면이 적혀 있으면 실제 상황과 본인의 역할을 구체적으로 확인합니다.",
    tails:["그 어려움은 어떻게 풀었나요?","모둠원들은 본인을 어떤 사람으로 기억할 것 같나요?"] },
  { id:"an-m1-91", area:["any"], intent:"motive", depth:1, kind:"experience", factor:"진로", needs:["topic"],
    text:"{topic|이} 학생부 여러 곳에 이어서 나오는데, 이 주제에 처음 관심을 갖게 된 계기는 무엇인가요?",
    purpose:"한 주제가 여러 영역에 걸쳐 기록되면 관심의 출발점과 이어진 흐름을 확인합니다.",
    tails:["관심이 깊어진 결정적인 활동은 무엇이었나요?","이 주제를 대학에서는 어떻게 이어 가고 싶나요?"] },
  { id:"da-g2-91", area:["dongari"], intent:"growth", depth:2, kind:"experience", factor:"진로", needs:[],
    text:"같은 동아리를 오래 이어 온 이유와, 그동안 자랐다고 생각하는 역량은 무엇인가요?",
    purpose:"한 동아리에 집중한 기록이 있으면 집중한 이유와 그 기간의 성장을 확인합니다.",
    tails:["그 역량이 드러난 장면을 하나 들어 주세요.","다른 동아리를 해 보고 싶었던 적은 없나요?"] },
  { id:"da-p2-91", area:["dongari"], intent:"process", depth:2, kind:"concept", factor:"학업", needs:[],
    text:"동아리에서 만든 결과물은 어떤 구조와 방법으로 만들었는지 설명해 주세요.",
    purpose:"개발·제작 활동이 있으면 결과물의 구성과 작동 방식을 말로 설명할 수 있는지 확인합니다.",
    tails:["그중 본인이 직접 맡은 부분은 어디였나요?","만들면서 가장 막혔던 지점은 무엇이었나요?"] },
  { id:"da-p1-91", area:["dongari"], intent:"process", depth:1, kind:"experience", factor:"공동체", needs:["role"],
    text:"{role|을} 맡아 동아리 활동을 하면서 겪은 어려움은 무엇이었나요?",
    purpose:"동아리를 만들거나 이끈 기록이 있으면 실제로 부딪힌 문제와 대처를 확인합니다.",
    tails:["그때 다르게 했으면 좋았겠다고 생각하는 점이 있나요?","다음 대표에게 무엇을 넘겨주었나요?"] },
  { id:"jy-g1-91", area:["jayul"], intent:"growth", depth:1, kind:"experience", factor:"공동체", needs:[],
    text:"이 교육이나 행사를 통해 새롭게 알게 된 점은 무엇인가요?",
    purpose:"단체 교육처럼 내용만 나열된 기록은 본인이 실제로 무엇을 얻었는지 다시 확인합니다.",
    tails:["그 뒤 생활에서 바뀐 점이 있나요?","그 내용을 친구에게 설명한다면 어떻게 말하겠습니까?"] },
  { id:"jy-g2-91", area:["jayul"], intent:"growth", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"꾸준히 이어 온 봉사활동이 본인에게 어떤 영향을 주었나요?",
    purpose:"봉사는 시간보다 왜 계속했는지, 본인에게 어떤 의미였는지를 확인합니다.",
    tails:["봉사하면서 가장 어려웠던 순간은 언제였나요?","그 경험이 지원 학과 공부와 이어지는 부분이 있나요?"] },
  { id:"jr-p1-91", area:["jinro"], intent:"process", depth:1, kind:"experience", factor:"진로", needs:[],
    text:"진로활동에서 세운 계획이나 조사한 내용 가운데 가장 관심이 가는 것은 무엇인가요?",
    purpose:"진로 계획·조사 기록이 있으면 주요 내용을 설명하게 하거나 하나로 좁혀 관심의 깊이를 확인합니다.",
    tails:["그 계획 가운데 이미 실천한 것은 무엇인가요?","계획이 바뀐 부분이 있다면 왜 바뀌었나요?"] },
  { id:"ht-m2-91", area:["haengteuk"], intent:"motive", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"선생님께서 본인을 이렇게 기록하신 이유는 무엇이라고 생각하나요?",
    purpose:"선생님의 평가 문구가 어떤 실제 행동에서 나왔는지 근거를 확인합니다.",
    tails:["그 모습이 드러난 장면을 하나 들어 주세요.","스스로 생각하기에도 맞는 평가인가요?"] },
  { id:"ht-p2-91", area:["haengteuk"], intent:"process", depth:2, kind:"experience", factor:"공동체", needs:[],
    text:"여러 학년에 비슷한 모습이 적혀 있는데, 그중 가장 의미 있었던 경험을 이야기해 주세요.",
    purpose:"학년마다 반복된 평가가 있으면 그것을 보여 주는 대표 사례를 확인합니다. 거창한 성과보다 실제 경험이 중요합니다.",
    tails:["그 경험으로 본인이 달라진 점은 무엇인가요?","그 모습이 대학 생활에서는 어떻게 드러날 것 같나요?"] },
  { id:"gm-m2-91", area:["gwamok"], intent:"motive", depth:2, kind:"experience", factor:"진로", needs:[],
    text:"관심 분야를 위해 스스로 골라 들은 과목이 있다면, 그 과목에서 얻은 것은 무엇인가요?",
    purpose:"과목 선택이 진로와 이어진 주도적인 선택이었는지 확인합니다.",
    tails:["그 과목에서 가장 어려웠던 단원은 무엇이었나요?","듣고 싶었지만 듣지 못한 과목이 있나요?"] },
];
